import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Limpando dados de teste...");

  await prisma.ticket.deleteMany();

  console.log("Criando tickets de teste...");

  const tickets = [
    {
      movideskId: 1001,
      protocol: "MOVI202608000001",
      subject: "Erro ao emitir nota fiscal",
      status: "Em Atendimento",
      baseStatus: "InAttendance",
      category: "Faturamento",
      urgency: "Alta",
      service: "ERP > Fiscal",
      owner: "João Silva",
      ownerTeam: "Suporte",
      client: "Cooperativa Alfa",
      createdDate: new Date("2026-08-10T08:30:00"),
      resolvedDate: null,
      closedDate: null,
      lifetimeMinutes: 1250,
      stoppedMinutes: 0,
    },
    {
      movideskId: 1002,
      protocol: "MOVI202608000002",
      subject: "Dúvida sobre cadastro de produto",
      status: "Resolvido",
      baseStatus: "Resolved",
      category: "Cadastro",
      urgency: "Média",
      service: "ERP > Cadastros",
      owner: "Maria Oliveira",
      ownerTeam: "Suporte",
      client: "Cooperativa Beta",
      createdDate: new Date("2026-08-08T09:10:00"),
      resolvedDate: new Date("2026-08-08T14:20:00"),
      closedDate: null,
      lifetimeMinutes: 310,
      stoppedMinutes: 20,
    },
    {
      movideskId: 1003,
      protocol: "MOVI202608000003",
      subject: "Sistema apresentando lentidão",
      status: "Em Atendimento",
      baseStatus: "InAttendance",
      category: "Performance",
      urgency: "Crítica",
      service: "ERP > Sistema",
      owner: "Carlos Santos",
      ownerTeam: "Infraestrutura",
      client: "Cooperativa Gama",
      createdDate: new Date("2026-08-11T07:45:00"),
      resolvedDate: null,
      closedDate: null,
      lifetimeMinutes: 890,
      stoppedMinutes: 0,
    },
    {
      movideskId: 1004,
      protocol: "MOVI202608000004",
      subject: "Erro na integração com sistema externo",
      status: "Parado",
      baseStatus: "Stopped",
      category: "Integração",
      urgency: "Alta",
      service: "Integrações",
      owner: "João Silva",
      ownerTeam: "Desenvolvimento",
      client: "Cooperativa Delta",
      createdDate: new Date("2026-08-05T10:00:00"),
      resolvedDate: null,
      closedDate: null,
      lifetimeMinutes: 5600,
      stoppedMinutes: 2400,
    },
    {
      movideskId: 1005,
      protocol: "MOVI202608000005",
      subject: "Solicitação de melhoria no relatório",
      status: "Novo",
      baseStatus: "New",
      category: "Melhoria",
      urgency: "Baixa",
      service: "Relatórios",
      owner: null,
      ownerTeam: "Produto",
      client: "Cooperativa Épsilon",
      createdDate: new Date("2026-08-12T11:30:00"),
      resolvedDate: null,
      closedDate: null,
      lifetimeMinutes: 180,
      stoppedMinutes: 0,
    },
    {
      movideskId: 1006,
      protocol: "MOVI202608000006",
      subject: "Usuário não consegue acessar o sistema",
      status: "Fechado",
      baseStatus: "Closed",
      category: "Acesso",
      urgency: "Alta",
      service: "Segurança > Usuários",
      owner: "Ana Souza",
      ownerTeam: "Suporte",
      client: "Cooperativa Alfa",
      createdDate: new Date("2026-08-06T08:00:00"),
      resolvedDate: new Date("2026-08-06T10:30:00"),
      closedDate: new Date("2026-08-06T11:00:00"),
      lifetimeMinutes: 180,
      stoppedMinutes: 0,
    },
    {
      movideskId: 1007,
      protocol: "MOVI202608000007",
      subject: "Erro recorrente no faturamento",
      status: "Em Atendimento",
      baseStatus: "InAttendance",
      category: "Faturamento",
      urgency: "Crítica",
      service: "ERP > Fiscal",
      owner: "Carlos Santos",
      ownerTeam: "Desenvolvimento",
      client: "Cooperativa Beta",
      createdDate: new Date("2026-08-01T13:00:00"),
      resolvedDate: null,
      closedDate: null,
      lifetimeMinutes: 9800,
      stoppedMinutes: 0,
    },
    {
      movideskId: 1008,
      protocol: "MOVI202608000008",
      subject: "Alteração de parâmetro do sistema",
      status: "Resolvido",
      baseStatus: "Resolved",
      category: "Configuração",
      urgency: "Média",
      service: "ERP > Configurações",
      owner: "Maria Oliveira",
      ownerTeam: "Suporte",
      client: "Cooperativa Gama",
      createdDate: new Date("2026-08-09T08:40:00"),
      resolvedDate: new Date("2026-08-09T12:10:00"),
      closedDate: null,
      lifetimeMinutes: 210,
      stoppedMinutes: 15,
    },
    {
      movideskId: 1009,
      protocol: "MOVI202608000009",
      subject: "Ticket aguardando retorno do cliente",
      status: "Parado",
      baseStatus: "Stopped",
      category: "Dúvida",
      urgency: "Média",
      service: "Atendimento",
      owner: "Ana Souza",
      ownerTeam: "Suporte",
      client: "Cooperativa Delta",
      createdDate: new Date("2026-08-03T15:20:00"),
      resolvedDate: null,
      closedDate: null,
      lifetimeMinutes: 7200,
      stoppedMinutes: 3800,
    },
    {
      movideskId: 1010,
      protocol: "MOVI202608000010",
      subject: "Erro na geração de relatório",
      status: "Fechado",
      baseStatus: "Closed",
      category: "Relatórios",
      urgency: "Alta",
      service: "Relatórios",
      owner: "João Silva",
      ownerTeam: "Desenvolvimento",
      client: "Cooperativa Épsilon",
      createdDate: new Date("2026-08-04T09:00:00"),
      resolvedDate: new Date("2026-08-04T16:00:00"),
      closedDate: new Date("2026-08-05T09:00:00"),
      lifetimeMinutes: 1860,
      stoppedMinutes: 120,
    },
  ];

  await prisma.ticket.createMany({
    data: tickets,
  });

  console.log(`${tickets.length} tickets criados com sucesso.`);
}

main()
  .catch((error) => {
    console.error("Erro ao executar seed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });