import { useEffect, useMemo, useState } from "react";
import { Box, Button, Card, CardContent, Chip, CircularProgress, Collapse, Divider, InputAdornment, Stack, TextField, Typography } from "@mui/material";
import { AccountTreeOutlined, ChevronRight, ExpandMore, FolderOutlined, HubOutlined, SearchOutlined, RuleOutlined, SchemaOutlined } from "@mui/icons-material";
import { api } from "../services/api";
import { SimerMapTree, type SimerTreeNode } from "./SimerMapTree";

type Process={id:number;name:string;sourceFile:string};
type Catalog={name:string;type:string;processes:Process[];children:Catalog[]};
type Node={id:number;externalId:string;name:string;kind:string;documentation:string|null};
type MapItem={id:number;sourceFile:string;mapName:string;nodeText:string;path:string;nodeKind:string|null;correlationScore?:number;reasons?:string[]};
type Detail={process:{id:number;name:string;folderPath:string|null;sourceFile:string};nodes:Node[];transitions:Array<{id:number;fromId:string;toId:string;name:string|null;condition:string|null}>;maps:MapItem[];correlations:MapItem[];stats:{steps:number;maps:number;technicalPoints:number;correlations:number}};

function Branch({node,onOpen,filter,level=0}:{node:Catalog;onOpen:(p:Process)=>void;filter:string;level?:number}){
 const [open,setOpen]=useState(level<2);const q=filter.toLowerCase();const visible=!q||node.name.toLowerCase().includes(q)||node.processes.some(p=>p.name.toLowerCase().includes(q))||node.children.some(c=>JSON.stringify(c).toLowerCase().includes(q));if(!visible)return null;
 return <Box><Box onClick={()=>setOpen(!open)} sx={{display:"flex",alignItems:"center",gap:.5,py:.55,pl:level*1.2,cursor:"pointer",borderRadius:1.5,"&:hover":{bgcolor:"action.hover"}}}>{open?<ExpandMore fontSize="small"/>:<ChevronRight fontSize="small"/>}<FolderOutlined sx={{fontSize:18,color:"warning.main"}}/><Typography variant="body2" sx={{fontWeight:level<2?800:650,flex:1}}>{node.name}</Typography><Chip size="small" variant="outlined" label={node.processes.length+node.children.length}/></Box><Collapse in={open||!!q}>{node.processes.filter(p=>!q||p.name.toLowerCase().includes(q)||node.name.toLowerCase().includes(q)).map(p=><Box key={p.id} onClick={()=>onOpen(p)} sx={{display:"flex",alignItems:"center",gap:.7,py:.55,pl:(level+2)*1.2,cursor:"pointer",borderRadius:1.5,"&:hover":{bgcolor:"action.selected",color:"primary.main"}}}><RuleOutlined sx={{fontSize:17}}/><Typography variant="body2">{p.name}</Typography></Box>)}{node.children.map(c=><Branch key={c.name} node={c} onOpen={onOpen} filter={filter} level={level+1}/>)}</Collapse></Box>
}

export function SystemExplorer({onOpenMap}:{onOpenMap:(item:MapItem)=>void}){
 const[catalog,setCatalog]=useState<Catalog|null>(null),[detail,setDetail]=useState<Detail|null>(null),[filter,setFilter]=useState(""),[loading,setLoading]=useState(false),[selectedMap,setSelectedMap]=useState<MapItem|null>(null),[mapTree,setMapTree]=useState<SimerTreeNode[]>([]);
 useEffect(()=>{void api.get<Catalog>("/simer-map/catalog").then(r=>setCatalog(r.data));},[]);
 async function openRoutine(p:Process){setLoading(true);setSelectedMap(null);setMapTree([]);try{setDetail((await api.get<Detail>(`/simer-map/catalog/routines/${p.id}`)).data);}finally{setLoading(false);}}
 async function openMap(item:MapItem){setSelectedMap(item);const r=await api.get<{items:SimerTreeNode[]}>("/simer-map/tree",{params:{sourceFile:item.sourceFile,focusId:item.id}});setMapTree(r.data.items);onOpenMap(item);}
 const path=detail?.process.folderPath?.replace(/\\/g," / ")??"";
 const descriptions=useMemo(()=>detail?.nodes.filter(n=>n.documentation).slice(0,4)??[],[detail]);
 return <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"310px minmax(0,1fr)"},gap:2,mt:2}}>
  <Card variant="outlined" sx={{borderRadius:3,alignSelf:"start",position:{lg:"sticky"},top:{lg:12},maxHeight:{lg:"calc(100vh - 110px)"},overflow:"auto"}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><AccountTreeOutlined color="primary"/><Box><Typography sx={{fontWeight:950}}>Estrutura do Sistema</Typography><Typography variant="caption" color="text.secondary">Navegue pela hierarquia funcional importada.</Typography></Box></Stack><TextField fullWidth size="small" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar módulo, seção ou rotina..." slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchOutlined fontSize="small"/></InputAdornment>}}}/><Divider sx={{my:1.2}}/>{catalog?<Branch node={catalog} onOpen={p=>void openRoutine(p)} filter={filter}/>:<Box sx={{textAlign:"center",py:4}}><CircularProgress size={24}/></Box>}</CardContent></Card>
  <Box>{loading?<Card variant="outlined" sx={{borderRadius:3}}><CardContent sx={{py:8,textAlign:"center"}}><CircularProgress/><Typography sx={{mt:1}}>Montando cadeia da rotina...</Typography></CardContent></Card>:detail?<Stack spacing={2}>
   <Card variant="outlined" sx={{borderRadius:3,background:"linear-gradient(135deg,rgba(24,199,122,.08),rgba(65,105,225,.04))"}}><CardContent><Typography variant="caption" color="text.secondary">{path}</Typography><Stack direction={{xs:"column",md:"row"}} spacing={1.5} sx={{alignItems:{md:"center"},mt:.5}}><Box sx={{width:46,height:46,borderRadius:2.5,bgcolor:"primary.main",color:"primary.contrastText",display:"grid",placeItems:"center"}}><HubOutlined/></Box><Box sx={{flex:1}}><Typography variant="h5" sx={{fontWeight:950}}>{detail.process.name}</Typography><Typography variant="body2" color="text.secondary">Rotina integrada: fluxo funcional, regras e implementação técnica encontrados na base importada.</Typography></Box><Chip color="success" label="Mapeada"/></Stack><Stack direction="row" spacing={.7} useFlexGap sx={{flexWrap:"wrap",mt:1.5}}><Chip label={`${detail.stats.steps} etapas funcionais`}/><Chip label={`${detail.stats.maps} mapas relacionados`}/><Chip label={`${detail.stats.technicalPoints} pontos técnicos`}/><Chip color="primary" label={`${detail.stats.correlations} correlações`}/></Stack></CardContent></Card>
   <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",xl:"1fr 1fr"},gap:2}}>
    <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><RuleOutlined color="primary"/><Typography sx={{fontWeight:900}}>Fluxo e Regra do Sistema</Typography></Stack>{descriptions.length>0&&<Box sx={{mb:1.2,p:1.2,bgcolor:"action.hover",borderRadius:2}}>{descriptions.map(n=><Typography key={n.id} variant="body2" sx={{mb:.5}}><b>{n.name}:</b> {n.documentation}</Typography>)}</Box>}<Box sx={{display:"flex",gap:1,overflowX:"auto",pb:1}}>{detail.nodes.map((n,i)=><Box key={n.id} sx={{display:"flex",alignItems:"center",flex:"0 0 auto"}}><Box sx={{width:190,minHeight:92,p:1.1,border:"1px solid",borderColor:n.kind==="gateway"?"warning.main":"divider",borderRadius:n.kind==="gateway"?5:2,bgcolor:"background.paper"}}><Chip size="small" variant="outlined" label={n.kind}/><Typography variant="body2" sx={{fontWeight:800,mt:.6}}>{n.name}</Typography>{n.documentation&&<Typography variant="caption" color="text.secondary" sx={{display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{n.documentation}</Typography>}</Box>{i<detail.nodes.length-1&&<Typography sx={{mx:.6,color:"text.disabled"}}>→</Typography>}</Box>)}</Box></CardContent></Card>
    <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><SchemaOutlined color="primary"/><Typography sx={{fontWeight:900}}>Mapa Técnico da Rotina</Typography></Stack><Stack spacing={.8}>{detail.maps.slice(0,8).map(m=><Box key={m.sourceFile} sx={{p:1,border:"1px solid",borderColor:selectedMap?.sourceFile===m.sourceFile?"primary.main":"divider",borderRadius:2}}><Stack direction="row" spacing={.7} sx={{alignItems:"center"}}><Chip size="small" label={m.nodeKind||"mapa"}/><Typography variant="body2" sx={{fontWeight:800,flex:1}}>{m.mapName}</Typography><Button size="small" onClick={()=>void openMap(m)}>Abrir</Button></Stack><Typography variant="caption" color="text.secondary">{m.path}</Typography></Box>)}</Stack>{selectedMap&&mapTree.length>0&&<Box sx={{mt:1.2,p:1,bgcolor:"action.hover",borderRadius:2,maxHeight:360,overflow:"auto"}}><SimerMapTree items={mapTree} focusId={selectedMap.id} onSelect={()=>{}} onFollowLink={()=>{}} onOpenContainer={()=>{}}/></Box>}</CardContent></Card>
   </Box>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Typography sx={{fontWeight:900,mb:1}}>Cadeia técnica correlacionada</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)"},gap:1}}>{detail.correlations.slice(0,12).map(m=><Box key={m.id} sx={{p:1.1,border:"1px solid",borderColor:"divider",borderRadius:2}}><Stack direction="row" spacing={.6} useFlexGap sx={{flexWrap:"wrap",alignItems:"center"}}><Chip size="small" color="success" label={`correlação ${m.correlationScore??0}`}/><Chip size="small" variant="outlined" label={m.nodeKind||"nó"}/><Typography variant="body2" sx={{fontWeight:850}}>{m.nodeText}</Typography></Stack><Typography variant="caption" color="text.secondary">{m.path}</Typography>{m.reasons?.map(x=><Chip key={x} size="small" variant="outlined" sx={{mt:.6,mr:.4}} label={x}/>)}<Button size="small" onClick={()=>void openMap(m)}>Abrir no mapa</Button></Box>)}</Box></CardContent></Card>
  </Stack>:<Card variant="outlined" sx={{borderRadius:3,minHeight:420,display:"grid",placeItems:"center"}}><CardContent sx={{textAlign:"center",maxWidth:520}}><AccountTreeOutlined sx={{fontSize:54,color:"text.disabled"}}/><Typography variant="h6" sx={{fontWeight:900,mt:1}}>Selecione uma rotina na árvore</Typography><Typography color="text.secondary">A árvore usa a hierarquia real importada das Regras do Sistema. Ao abrir uma rotina, o TechLead Hub cruza o fluxo funcional com os mapas .mm e apresenta a cadeia técnica relacionada.</Typography></CardContent></Card>}</Box>
 </Box>
}