import { useEffect, useMemo, useState } from "react";
import { Box, Button, Card, CardContent, Chip, CircularProgress, Collapse, Divider, InputAdornment, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { AccountTreeOutlined, AltRouteOutlined, ChevronRight, ContentCopyOutlined, DescriptionOutlined, ExpandMore, FolderOutlined, HubOutlined, InfoOutlined, OpenInNewOutlined, RuleOutlined, SearchOutlined, SchemaOutlined, SettingsOutlined } from "@mui/icons-material";
import { api } from "../services/api";
import { SimerMapTree, type SimerTreeNode } from "./SimerMapTree";

type Process={id:number;name:string;sourceFile:string;folderPath?:string|null;steps?:number};
type Catalog={name:string;type:string;processes:Process[];children:Catalog[]};
type Node={id:number;externalId:string;name:string;kind:string;documentation:string|null};
type MapItem={id:number;sourceFile:string;mapName:string;nodeText:string;path:string;nodeKind:string|null;correlationScore?:number;reasons?:string[]};
type Element={id:number;name:string;kind:string;mapName:string;path:string;score:number};
type Detail={process:{id:number;name:string;folderPath:string|null;sourceFile:string};nodes:Node[];transitions:Array<{id:number;fromId:string;toId:string;name:string|null;condition:string|null}>;maps:MapItem[];correlations:MapItem[];elements:Element[];relatedProcesses:Process[];stats:{steps:number;maps:number;technicalPoints:number;correlations:number}};

function Branch({node,onOpen,filter,level=0,selected}:{node:Catalog;onOpen:(p:Process)=>void;filter:string;level?:number;selected?:number}){
 const [open,setOpen]=useState(level<2);const q=filter.toLowerCase().trim();const blob=JSON.stringify(node).toLowerCase();if(q&&!blob.includes(q))return null;
 return <Box><Box onClick={()=>setOpen(!open)} sx={{display:"flex",alignItems:"center",gap:.5,py:.5,pl:level*.8,cursor:"pointer",borderRadius:1.5,"&:hover":{bgcolor:"action.hover"}}}>{open?<ExpandMore sx={{fontSize:18}}/>:<ChevronRight sx={{fontSize:18}}/>}<FolderOutlined sx={{fontSize:17,color:level<2?"warning.main":"text.secondary"}}/><Typography variant="body2" sx={{fontWeight:level<2?850:650,flex:1}}>{node.name}</Typography><Chip size="small" variant="outlined" label={node.processes.length+node.children.length} sx={{height:20}}/></Box><Collapse in={open||!!q}>{node.processes.filter(p=>!q||p.name.toLowerCase().includes(q)||node.name.toLowerCase().includes(q)).map(p=><Box key={p.id} onClick={()=>onOpen(p)} sx={{display:"flex",alignItems:"center",gap:.7,py:.55,pl:(level+2)*.8,cursor:"pointer",borderRadius:1.5,bgcolor:selected===p.id?"rgba(24,199,122,.14)":"transparent",color:selected===p.id?"primary.main":"inherit","&:hover":{bgcolor:"action.selected"}}}><DescriptionOutlined sx={{fontSize:16}}/><Typography variant="body2" sx={{fontWeight:selected===p.id?850:500,flex:1}}>{p.name}</Typography>{p.steps!=null&&<Chip size="small" label={p.steps} sx={{height:19}}/>}</Box>)}{node.children.map(c=><Branch key={c.name} node={c} onOpen={onOpen} filter={filter} level={level+1} selected={selected}/>)}</Collapse></Box>
}

function Empty(){return <Card variant="outlined" sx={{borderRadius:3,minHeight:500,display:"grid",placeItems:"center"}}><CardContent sx={{textAlign:"center",maxWidth:560}}><AccountTreeOutlined sx={{fontSize:58,color:"text.disabled"}}/><Typography variant="h6" sx={{fontWeight:950,mt:1}}>Selecione uma rotina na estrutura</Typography><Typography color="text.secondary">Abra módulo, seção e processo na árvore. A rotina será apresentada com regra Bizagi, mapas .mm, elementos técnicos e relacionamentos encontrados automaticamente.</Typography></CardContent></Card>}

export function SystemExplorer({onOpenMap}:{onOpenMap:(item:MapItem)=>void}){
 const[catalog,setCatalog]=useState<Catalog|null>(null),[detail,setDetail]=useState<Detail|null>(null),[filter,setFilter]=useState(""),[loading,setLoading]=useState(false),[selectedMap,setSelectedMap]=useState<MapItem|null>(null),[mapTree,setMapTree]=useState<SimerTreeNode[]>([]),[tab,setTab]=useState(0);
 useEffect(()=>{void api.get<Catalog>("/simer-map/catalog").then(r=>setCatalog(r.data));},[]);
 async function openRoutine(p:Process){setLoading(true);setSelectedMap(null);setMapTree([]);setTab(0);try{setDetail((await api.get<Detail>(`/simer-map/catalog/routines/${p.id}`)).data);}finally{setLoading(false);}}
 async function openMap(item:MapItem){setSelectedMap(item);const r=await api.get<{items:SimerTreeNode[]}>("/simer-map/tree",{params:{sourceFile:item.sourceFile,focusId:item.id}});setMapTree(r.data.items);onOpenMap(item);}
 const path=(detail?.process.folderPath??"").replace(/\\/g," / ");
 const grouped=useMemo(()=>{const g=new Map<string,Element[]>();for(const e of detail?.elements??[]){const k=e.kind||"elemento";g.set(k,[...(g.get(k)??[]),e]);}return [...g.entries()];},[detail]);
 const description=detail?.nodes.find(n=>n.documentation)?.documentation;
 return <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"300px minmax(0,1fr) 290px"},gap:1.5,mt:2,alignItems:"start"}}>
  <Card variant="outlined" sx={{borderRadius:3,position:{lg:"sticky"},top:{lg:12},maxHeight:{lg:"calc(100vh - 110px)"},overflow:"auto"}}><CardContent sx={{p:1.7}}><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><AccountTreeOutlined color="primary"/><Box><Typography sx={{fontWeight:950}}>Estrutura do Sistema</Typography><Typography variant="caption" color="text.secondary">Hierarquia funcional do SIMER.</Typography></Box></Stack><Stack direction="row" spacing=.7><TextField fullWidth size="small" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar no sistema..." slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchOutlined sx={{fontSize:18}}/></InputAdornment>}}}/><Button variant="outlined" sx={{minWidth:40,p:0}}><SettingsOutlined fontSize="small"/></Button></Stack><Divider sx={{my:1.1}}/>{catalog?<Branch node={catalog} onOpen={p=>void openRoutine(p)} filter={filter} selected={detail?.process.id}/>:<Box sx={{textAlign:"center",py:4}}><CircularProgress size={24}/></Box>}</CardContent></Card>

  <Box>{loading?<Card variant="outlined" sx={{borderRadius:3}}><CardContent sx={{py:10,textAlign:"center"}}><CircularProgress/><Typography sx={{mt:1}}>Cruzando regra, fluxo e mapa técnico...</Typography></CardContent></Card>:!detail?<Empty/>:<Stack spacing={1.5}>
   <Card variant="outlined" sx={{borderRadius:3,overflow:"hidden"}}><CardContent sx={{p:1.8}}><Typography variant="caption" color="text.secondary">SIMER {path&&`› ${path.replace(/ \/ /g," › ")}`}</Typography><Stack direction={{xs:"column",md:"row"}} spacing={1.3} sx={{alignItems:{md:"center"},mt:.7}}><Box sx={{width:48,height:48,borderRadius:"50%",display:"grid",placeItems:"center",bgcolor:"rgba(24,199,122,.16)",color:"primary.main"}}><HubOutlined/></Box><Box sx={{flex:1}}><Typography variant="h5" sx={{fontWeight:950}}>{detail.process.name}</Typography><Typography variant="body2" color="text.secondary">{description||"Rotina identificada na base funcional e correlacionada automaticamente com os mapas técnicos do SIMER."}</Typography></Box><Chip color="success" size="small" label="Mapeada"/></Stack><Stack direction="row" spacing=.7 useFlexGap sx={{flexWrap:"wrap",mt:1.3}}><Chip size="small" label={`${detail.stats.steps} etapas`}/><Chip size="small" label={`${detail.stats.maps} mapas`}/><Chip size="small" label={`${detail.stats.technicalPoints} pontos técnicos`}/><Chip size="small" color="primary" label={`${detail.stats.correlations} correlações`}/></Stack></CardContent><Divider/><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto" sx={{px:1}}><Tab label="Visão Geral"/><Tab label="Fluxo de Negócio"/><Tab label="Mapa Técnico"/><Tab label="Campos e Regras"/><Tab label="Serviços e Integrações"/></Tabs></Card>

   {tab===0&&<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",xl:"1fr 1fr"},gap:1.5}}>
    <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><DescriptionOutlined color="primary"/><Typography sx={{fontWeight:900}}>Descrição da Rotina</Typography></Stack><Typography variant="body2" sx={{lineHeight:1.75}}>{description||"A documentação detalhada desta rotina ainda não está preenchida no fluxo importado. As etapas e associações técnicas abaixo foram obtidas das bases Bizagi e .mm."}</Typography><Divider sx={{my:1.4}}/><Typography variant="subtitle2" sx={{fontWeight:850,mb:.6}}>Etapas principais</Typography>{detail.nodes.slice(0,5).map((n,i)=><Stack key={n.id} direction="row" spacing={1} sx={{alignItems:"center",py:.35}}><Chip size="small" label={i+1} sx={{width:25}}/><Typography variant="body2">{n.name}</Typography></Stack>)}</CardContent></Card>
    <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><InfoOutlined color="primary"/><Typography sx={{fontWeight:900}}>Informações</Typography></Stack><Box sx={{display:"grid",gridTemplateColumns:"145px 1fr",rowGap:.75}}>{[["Caminho",path||"SIMER"],["Fonte funcional",detail.process.sourceFile],["Etapas",detail.stats.steps],["Mapas técnicos",detail.stats.maps],["Pontos técnicos",detail.stats.technicalPoints],["Correlações",detail.stats.correlations]].map(([k,v])=><Box key={String(k)} sx={{display:"contents"}}><Typography variant="body2" color="text.secondary">{k}</Typography><Typography variant="body2" sx={{fontWeight:650,overflowWrap:"anywhere"}}>{v}</Typography></Box>)}</Box></CardContent></Card>
    <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><AltRouteOutlined color="primary"/><Typography sx={{fontWeight:900}}>Fluxo de Negócio (Bizagi)</Typography><Chip size="small" label={`${detail.nodes.length} etapas`}/></Stack><Box sx={{display:"flex",gap:.7,overflowX:"auto",pb:1}}>{detail.nodes.slice(0,8).map((n,i)=><Box key={n.id} sx={{display:"flex",alignItems:"center",flex:"0 0 auto"}}><Box sx={{width:145,minHeight:74,p:1,border:"1px solid",borderColor:n.kind==="gateway"?"warning.main":"divider",borderRadius:n.kind==="gateway"?5:2,bgcolor:"background.paper"}}><Typography variant="caption" color="text.secondary">{n.kind}</Typography><Typography variant="body2" sx={{fontWeight:800}}>{n.name}</Typography></Box>{i<Math.min(detail.nodes.length,8)-1&&<Typography sx={{mx:.2,color:"text.disabled"}}>→</Typography>}</Box>)}</Box><Button size="small" onClick={()=>setTab(1)}>Abrir fluxo completo</Button></CardContent></Card>
    <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><SchemaOutlined color="primary"/><Typography sx={{fontWeight:900}}>Mapa Técnico (.mm)</Typography><Chip size="small" label={`${detail.maps.length} mapas`}/></Stack>{detail.maps.slice(0,4).map(m=><Box key={m.sourceFile} sx={{py:.7,borderBottom:"1px solid",borderColor:"divider"}}><Stack direction="row" spacing=.7 sx={{alignItems:"center"}}><Typography variant="body2" sx={{fontWeight:800,flex:1}}>{m.mapName}</Typography><Button size="small" onClick={()=>void openMap(m)}>Abrir</Button></Stack><Typography variant="caption" color="text.secondary">{m.path}</Typography></Box>)}<Button size="small" sx={{mt:.7}} onClick={()=>setTab(2)}>Ver mapa técnico</Button></CardContent></Card>
   </Box>}

   {tab===1&&<Card variant="outlined" sx={{borderRadius:3}}><CardContent><Typography sx={{fontWeight:900,mb:1}}>Fluxo funcional completo</Typography><Box sx={{display:"flex",gap:1,overflowX:"auto",pb:1.5}}>{detail.nodes.map((n,i)=><Box key={n.id} sx={{display:"flex",alignItems:"center",flex:"0 0 auto"}}><Box sx={{width:205,minHeight:115,p:1.2,border:"1px solid",borderColor:n.kind==="gateway"?"warning.main":"divider",borderRadius:n.kind==="gateway"?6:2.5}}><Chip size="small" variant="outlined" label={n.kind}/><Typography variant="body2" sx={{fontWeight:850,mt:.6}}>{n.name}</Typography>{n.documentation&&<Typography variant="caption" color="text.secondary">{n.documentation}</Typography>}</Box>{i<detail.nodes.length-1&&<Typography sx={{mx:.5}}>→</Typography>}</Box>)}</Box></CardContent></Card>}

   {tab===2&&<Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={1} sx={{mb:1}}><Box sx={{flex:1}}><Typography sx={{fontWeight:900}}>Mapa Técnico da Rotina</Typography><Typography variant="body2" color="text.secondary">Selecione um mapa para abrir apenas o recorte associado à rotina.</Typography></Box></Stack><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"260px 1fr"},gap:1.5}}><Stack spacing=.7>{detail.maps.map(m=><Box key={m.sourceFile} onClick={()=>void openMap(m)} sx={{p:1,border:"1px solid",borderColor:selectedMap?.sourceFile===m.sourceFile?"primary.main":"divider",borderRadius:2,cursor:"pointer",bgcolor:selectedMap?.sourceFile===m.sourceFile?"action.selected":"transparent"}}><Typography variant="body2" sx={{fontWeight:850}}>{m.mapName}</Typography><Typography variant="caption" color="text.secondary">{m.nodeText}</Typography></Box>)}</Stack><Box sx={{minHeight:340,p:1,border:"1px solid",borderColor:"divider",borderRadius:2,overflow:"auto"}}>{mapTree.length?<SimerMapTree items={mapTree} focusId={selectedMap?.id??null} onSelect={()=>{}} onFollowLink={()=>{}} onOpenContainer={()=>{}}/>:<Box sx={{textAlign:"center",py:8}}><SchemaOutlined sx={{fontSize:44,color:"text.disabled"}}/><Typography color="text.secondary">Selecione um mapa relacionado.</Typography></Box>}</Box></Box></CardContent></Card>}

   {(tab===3||tab===4)&&<Card variant="outlined" sx={{borderRadius:3}}><CardContent><Typography sx={{fontWeight:900,mb:1}}>{tab===3?"Campos e Regras":"Serviços e Integrações"}</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)"},gap:1}}>{grouped.filter(([kind])=>tab===3?!/service|servi|method|metodo|integra/i.test(kind):/service|servi|method|metodo|integra/i.test(kind)).flatMap(([,els])=>els).map(e=><Box key={e.id} sx={{p:1.1,border:"1px solid",borderColor:"divider",borderRadius:2}}><Stack direction="row" spacing=.6 sx={{alignItems:"center"}}><Chip size="small" variant="outlined" label={e.kind}/><Typography variant="body2" sx={{fontWeight:850}}>{e.name}</Typography></Stack><Typography variant="caption" color="text.secondary">{e.mapName} · {e.path}</Typography></Box>)}</Box></CardContent></Card>}
  </Stack>}</Box>

  <Stack spacing={1.5} sx={{position:{lg:"sticky"},top:{lg:12}}}>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent sx={{p:1.5}}><Stack direction="row" spacing={1}><Button fullWidth variant="contained" startIcon={<HubOutlined/>} disabled={!detail}>Investigar</Button><Button variant="outlined" disabled={!detail}>☆</Button></Stack></CardContent></Card>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Typography sx={{fontWeight:900,mb:1}}>Elementos Relacionados</Typography>{detail?grouped.slice(0,5).map(([kind,els])=><Box key={kind} sx={{mb:1}}><Stack direction="row" sx={{justifyContent:"space-between",mb:.4}}><Typography variant="caption" sx={{fontWeight:850,textTransform:"capitalize"}}>{kind}</Typography><Chip size="small" label={els.length}/></Stack>{els.slice(0,3).map(e=><Box key={e.id} sx={{py:.35}}><Typography variant="body2" sx={{fontWeight:750}}>{e.name}</Typography><Typography variant="caption" color="text.secondary">{e.mapName}</Typography></Box>)}</Box>):<Typography variant="body2" color="text.secondary">Selecione uma rotina.</Typography>}</CardContent></Card>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Typography sx={{fontWeight:900,mb:1}}>Rotinas Relacionadas</Typography>{detail?.relatedProcesses?.length?detail.relatedProcesses.map(p=><Box key={p.id} onClick={()=>void openRoutine(p)} sx={{display:"flex",alignItems:"center",gap:.7,py:.65,cursor:"pointer","&:hover":{color:"primary.main"}}}><DescriptionOutlined sx={{fontSize:17}}/><Typography variant="body2" sx={{fontWeight:750,flex:1}}>{p.name}</Typography><Chip size="small" label={p.steps??0}/></Box>):<Typography variant="body2" color="text.secondary">Nenhuma rotina irmã identificada.</Typography>}</CardContent></Card>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Typography sx={{fontWeight:900,mb:1}}>Ações Rápidas</Typography><Stack spacing=.7><Button variant="outlined" startIcon={<OpenInNewOutlined/>} disabled={!detail?.maps.length} onClick={()=>detail?.maps[0]&&void openMap(detail.maps[0])}>Abrir no mapa</Button><Button variant="outlined" startIcon={<RuleOutlined/>} disabled={!detail} onClick={()=>setTab(1)}>Ver regra completa</Button><Button variant="text" startIcon={<ContentCopyOutlined/>} disabled={!detail} onClick={()=>detail&&void navigator.clipboard.writeText(`SIMER / ${path} / ${detail.process.name}`)}>Copiar caminho</Button></Stack></CardContent></Card>
  </Stack>
 </Box>
}