import { useEffect, useMemo, useRef, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, LinearProgress, Stack, TextField, Tooltip, Typography } from "@mui/material";
import { AccountTreeOutlined, AltRouteOutlined, AutoAwesomeOutlined, DescriptionOutlined, FolderOpenOutlined, RuleOutlined, SearchOutlined, UploadFileOutlined } from "@mui/icons-material";
import { api } from "../services/api";

type RuleResult={id:number;processId:number;name:string;kind:string;documentation:string|null;processName:string;sourceFile:string;folderPath:string|null;score:number};
type RuleNode={id:number;externalId:string;name:string;kind:string;documentation:string|null;x:number|null;y:number|null};
type Transition={id:number;fromId:string;toId:string;name:string|null;condition:string|null};
type Flow={process:{id:number;name:string;sourceFile:string;folderPath:string|null}|null;nodes:RuleNode[];transitions:Transition[];focusId:number|null};
type Summary={processes:number;nodes:number;transitions:number};
type ImportResult={sourceFile:string;processes:number;nodes:number;transitions:number;created:number;updated:number};
const folderProps={webkitdirectory:"",directory:""} as Record<string,string>;
function toBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]??"");r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}

type ImportSnapshot={running:boolean;progress:number|null;message:string};
let importSnapshot:ImportSnapshot={running:false,progress:null,message:""};
const importListeners=new Set<(s:ImportSnapshot)=>void>();
function publishImport(patch:Partial<ImportSnapshot>){importSnapshot={...importSnapshot,...patch};for(const listener of importListeners)listener(importSnapshot);}
async function runBpmImport(files:File[]){
 if(importSnapshot.running)return;publishImport({running:true,progress:0,message:""});let n=0,created=0,updated=0,failed=0;
 for(let i=0;i<files.length;i++){const file=files[i]!;try{const r=await api.post<ImportResult>("/simer-map/rules/import",{sourceFile:(file as File&{webkitRelativePath?:string}).webkitRelativePath||file.name,base64:await toBase64(file)});n+=r.data.nodes;created+=r.data.created??0;updated+=r.data.updated??0;}catch{failed++;}finally{publishImport({progress:Math.round(((i+1)/files.length)*100)});}}
 const parts=[`${files.length-failed} arquivo(s) processado(s)`,`${created} novo(s)`,`${updated} atualizado(s)`,`${n} etapa(s)`];if(failed)parts.push(`${failed} falha(s)`);
 publishImport({running:false,progress:null,message:`Base de regras atualizada: ${parts.join(" · ")}.`});
}

export function SystemRulePanel({initialQuery=""}:{initialQuery?:string}){
 const fileRef=useRef<HTMLInputElement|null>(null),folderRef=useRef<HTMLInputElement|null>(null),zipRef=useRef<HTMLInputElement|null>(null);
 const[query,setQuery]=useState(initialQuery),[results,setResults]=useState<RuleResult[]>([]),[summary,setSummary]=useState<Summary|null>(null),[flow,setFlow]=useState<Flow|null>(null),[loading,setLoading]=useState(false),[importState,setImportState]=useState(importSnapshot);
 useEffect(()=>{setQuery(initialQuery);},[initialQuery]);
 async function loadSummary(){try{setSummary((await api.get<Summary>("/simer-map/rules/summary")).data);}catch{/* base ainda não inicializada */}}
 useEffect(()=>{void loadSummary();const listener=(s:ImportSnapshot)=>{setImportState(s);if(!s.running)void loadSummary();};importListeners.add(listener);return()=>{importListeners.delete(listener);};},[]);
 async function search(){if(!query.trim())return;setLoading(true);publishImport({message:""});setFlow(null);try{const r=await api.get<{items:RuleResult[]}>("/simer-map/rules/search",{params:{q:query.trim(),limit:20}});setResults(r.data.items);if(!r.data.items.length)publishImport({message:"Nenhuma Regra do Sistema relacionada foi localizada."});}catch{publishImport({message:"Não foi possível consultar as Regras do Sistema."});}finally{setLoading(false);}}
 async function open(item:RuleResult){setLoading(true);try{setFlow((await api.get<Flow>(`/simer-map/rules/${item.processId}/flow`,{params:{focusId:item.id}})).data);}finally{setLoading(false);}}
 async function importFiles(list:FileList|null){if(!list?.length)return;const selected=Array.from(list);const files=selected.filter(f=>/\.(bpm|zip)$/i.test(f.name));if(!files.length){const sample=selected.slice(0,3).map(f=>(f as File&{webkitRelativePath?:string}).webkitRelativePath||f.name).join(", ");publishImport({message:`Nenhum .bpm/.zip importável foi encontrado. Selecionados: ${selected.length}${sample?` · ${sample}`:""}. Para ZIP, use o botão "ZIP Bizagi"; para uma pasta extraída, use "Importar pasta".`});return;}if(importSnapshot.running){publishImport({message:"Já existe uma importação de BPM em andamento. Ela continuará mesmo ao trocar de tela."});return;}void runBpmImport(files);if(fileRef.current)fileRef.current.value="";if(folderRef.current)folderRef.current.value="";if(zipRef.current)zipRef.current.value="";}

 const outgoing=useMemo(()=>{const m=new Map<string,Transition[]>();for(const x of flow?.transitions??[]){const a=m.get(x.fromId)??[];a.push(x);m.set(x.fromId,a);}return m;},[flow]);
 return <Card variant="outlined" sx={{borderRadius:3,overflow:"hidden",background:"linear-gradient(145deg, rgba(17,24,39,.02), rgba(24,199,122,.045))"}}>
  <CardContent sx={{p:{xs:2,md:2.5},"&:last-child":{pb:{xs:2,md:2.5}}}}>
   <Stack direction={{xs:"column",lg:"row"}} spacing={1.5} sx={{alignItems:{lg:"center"},mb:1.5}}>
    <Box sx={{display:"flex",gap:1.2,alignItems:"center",flex:1}}><Box sx={{width:42,height:42,borderRadius:2.2,display:"grid",placeItems:"center",bgcolor:"primary.main",color:"primary.contrastText"}}><RuleOutlined/></Box><Box><Typography sx={{fontWeight:950,fontSize:"1.05rem"}}>Regra do Sistema</Typography><Typography variant="body2" color="text.secondary">Consulte o comportamento esperado da rotina e confronte a regra funcional com o Mapa SIMER.</Typography></Box></Box>
    <Stack direction="row" spacing={.7} useFlexGap sx={{flexWrap:"wrap",justifyContent:{lg:"flex-end"}}}>{summary&&<><Chip icon={<AccountTreeOutlined/>} label={`${summary.processes} processos`} size="small"/><Chip icon={<AltRouteOutlined/>} label={`${summary.nodes} etapas`} size="small"/></>}<Button component="label" size="small" variant="outlined" startIcon={<UploadFileOutlined/>}>Arquivos BPM<input ref={fileRef} hidden type="file" multiple accept=".bpm" onChange={e=>void importFiles(e.target.files)}/></Button><Button component="label" size="small" variant="outlined" startIcon={<UploadFileOutlined/>}>ZIP Bizagi<input ref={zipRef} hidden type="file" accept=".zip,application/zip,application/x-zip-compressed" onChange={e=>void importFiles(e.target.files)}/></Button><Button component="label" size="small" variant="contained" startIcon={<FolderOpenOutlined/>}>Importar pasta<input ref={folderRef} hidden type="file" multiple {...folderProps} onChange={e=>void importFiles(e.target.files)}/></Button></Stack>
   </Stack>
   <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"minmax(0,1fr) 190px"},gap:1,alignItems:"stretch"}}><TextField fullWidth size="small" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void search()} placeholder="Campo, rotina ou regra. Ex.: lote no receituário, nota fiscal vinculada, responsável técnico..." slotProps={{input:{startAdornment:<SearchOutlined sx={{mr:1,color:"text.disabled",fontSize:20}}/>}}}/><Button variant="contained" startIcon={<SearchOutlined/>} onClick={()=>void search()} disabled={loading||importState.running||!query.trim()} sx={{minHeight:40,whiteSpace:"nowrap",fontWeight:800,borderRadius:2}}>Investigar regra</Button></Box>
   {importState.progress!==null&&<Box sx={{mt:1.5}}><LinearProgress variant="determinate" value={importState.progress}/><Typography variant="caption" color="text.secondary">{importState.progress}% · importando e conciliando regras Bizagi</Typography></Box>}
   {importState.message&&<Alert sx={{mt:1.5}} severity={importState.message.includes("falha")||importState.message.startsWith("Não foi")||importState.message.startsWith("Nenhum")?"warning":"success"}>{importState.message}</Alert>}
   {loading&&importState.progress===null&&<Box sx={{py:3,textAlign:"center"}}><CircularProgress size={26}/></Box>}
   {!loading&&results.length>0&&!flow&&<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"repeat(2,1fr)"},gap:1,mt:1.5}}>{results.map(r=><Box key={r.id} onClick={()=>void open(r)} sx={{p:1.4,border:"1px solid",borderColor:"divider",borderRadius:2.5,cursor:"pointer",bgcolor:"background.paper","&:hover":{borderColor:"primary.main",boxShadow:"0 8px 28px rgba(16,24,40,.08)"}}}><Stack direction="row" spacing={.7} sx={{alignItems:"center"}}><Chip size="small" color={r.kind==="gateway"?"warning":"success"} variant="outlined" label={r.kind}/><Typography sx={{fontWeight:850}}>{r.name}</Typography></Stack><Typography variant="caption" color="primary.main">{r.processName}</Typography>{r.folderPath&&<Typography variant="caption" color="text.secondary" sx={{display:"block"}}>⌂ {r.folderPath}</Typography>}{r.documentation&&<Typography variant="body2" color="text.secondary" sx={{mt:.5,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{r.documentation}</Typography>}</Box>)}</Box>}
   {flow?.process&&<Box sx={{mt:1.5}}><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><AutoAwesomeOutlined color="primary"/><Box sx={{flex:1}}><Typography sx={{fontWeight:900}}>{flow.process.name}</Typography><Typography variant="caption" color="text.secondary">{flow.process.folderPath?`${flow.process.folderPath} / `:""}{flow.process.sourceFile.replace(/^.*[\\/]/,"")}</Typography></Box><Button size="small" onClick={()=>setFlow(null)}>Voltar aos resultados</Button></Stack><Divider sx={{mb:1.5}}/><Box sx={{display:"flex",gap:1,overflowX:"auto",pb:1.5,scrollSnapType:"x proximity"}}>{flow.nodes.map((n,i)=>{const links=outgoing.get(n.externalId)??[];const active=n.id===flow.focusId;return <Box key={n.id} sx={{display:"flex",alignItems:"center",flex:"0 0 auto"}}><Tooltip title={n.documentation||n.name} placement="top"><Box sx={{width:220,minHeight:116,p:1.4,border:"1px solid",borderColor:active?"primary.main":"divider",borderRadius:n.kind==="gateway"?5:2.5,bgcolor:active?"action.selected":"background.paper",boxShadow:active?"0 0 0 3px rgba(24,199,122,.10)":"none",scrollSnapAlign:"start"}}><Stack direction="row" spacing={.7} sx={{alignItems:"center",mb:.6}}>{n.kind==="gateway"?<AltRouteOutlined fontSize="small"/>:<DescriptionOutlined fontSize="small"/>}<Chip size="small" variant="outlined" label={n.kind}/></Stack><Typography variant="body2" sx={{fontWeight:850}}>{n.name}</Typography>{n.documentation&&<Typography variant="caption" color="text.secondary" sx={{mt:.5,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{n.documentation}</Typography>}{links.map(x=><Chip key={x.id} size="small" sx={{mt:.7,mr:.4}} label={x.condition||x.name||"próxima etapa"}/>)}</Box></Tooltip>{i<flow.nodes.length-1&&<Typography sx={{mx:.8,color:"text.disabled",fontWeight:900}}>→</Typography>}</Box>})}</Box><Alert icon={<AutoAwesomeOutlined/>} severity="info">Use este recorte como <b>comportamento esperado</b>. Compare a etapa selecionada com serviços, containers, campos e vínculos encontrados no Mapa SIMER antes de concluir a causa do atendimento.</Alert></Box>}
  </CardContent>
 </Card>;
}