import JSZip from "jszip";
import { prisma } from "../database/prisma";

type RuleNode={externalId:string;name:string;kind:string;documentation:string|null;lane:string|null;x:number|null;y:number|null};
type RuleTransition={externalId:string;fromId:string;toId:string;name:string|null;condition:string|null};
const decode=(v:string)=>v.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");
const clean=(v:string)=>decode(v).replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim();
const attr=(s:string,n:string)=>{const m=s.match(new RegExp("\\b"+n+'="([^"]*)"',"i"));return m?decode(m[1]??""):null;};
function block(xml:string,tag:string){return [...xml.matchAll(new RegExp("<"+tag+"\\b[\\s\\S]*?<\\/"+tag+">","gi"))].map(x=>x[0]);}
function parseDiagram(xml:string,sourceFile:string){
 const pkg=xml.match(/<Package\b[^>]*>/i)?.[0]??"";const processName=attr(pkg,"Name")||sourceFile.replace(/.*[\\/]/,"").replace(/\.bpm$/i,"");
 const nodes:RuleNode[]=[];
 for(const a of block(xml,"Activity")){const head=a.match(/<Activity\b[^>]*>/i)?.[0]??"";const id=attr(head,"Id");if(!id)continue;const name=attr(head,"Name")||(/<StartEvent\b/i.test(a)?"Início":/<EndEvent\b/i.test(a)?"Fim":"Etapa");
  const doc=clean(a.match(/<Documentation>([\s\S]*?)<\/Documentation>/i)?.[1]??a.match(/<Description>([\s\S]*?)<\/Description>/i)?.[1]??"");
  const kind=/<Route\b/i.test(a)?"gateway":/<StartEvent\b/i.test(a)?"inicio":/<EndEvent\b/i.test(a)?"fim":/<SubFlow\b/i.test(a)?"subprocesso":"atividade";
  const g=a.match(/<Coordinates\b[^>]*>/i)?.[0]??"";nodes.push({externalId:id,name,kind,documentation:doc||null,lane:null,x:Number(attr(g,"XCoordinate"))||null,y:Number(attr(g,"YCoordinate"))||null});}
 const transitions:RuleTransition[]=[];
 for(const t of block(xml,"Transition")){const h=t.match(/<Transition\b[^>]*>/i)?.[0]??"";const id=attr(h,"Id"),from=attr(h,"From"),to=attr(h,"To");if(!id||!from||!to)continue;const condition=clean(t.match(/<Condition[^>]*>([\s\S]*?)<\/Condition>/i)?.[1]??"");transitions.push({externalId:id,fromId:from,toId:to,name:attr(h,"Name"),condition:condition||null});}
 return{processName,nodes,transitions};
}

function webKind(type:string){const t=type.toLowerCase();if(t.includes("gateway"))return "gateway";if(t.includes("start"))return "inicio";if(t.includes("end"))return "fim";if(t.includes("callactivity")||t.includes("subprocess"))return "subprocesso";return "atividade";}
function parseWebPage(page:any){const nodes:RuleNode[]=[];const visit=(items:any[])=>{for(const e of items??[]){const type=String(e?.elementType??"");const children=Array.isArray(e?.pageElements)?e.pageElements:[];if(type!=="Participant"&&type!=="Lane"&&type!=="SequenceFlow"&&e?.id){const point=e?.imageBounds?.points?.[0];const conditions=children.filter((x:any)=>String(x?.elementType)==="SequenceFlow").map((x:any)=>String(x?.name??"").trim()).filter(Boolean);const description=clean(String(e?.description??""));nodes.push({externalId:String(e.id),name:String(e?.name??type??"Etapa").trim()||"Etapa",kind:webKind(type),documentation:[description,conditions.length?"Saídas: "+conditions.join(" | "):""].filter(Boolean).join(" · ")||null,lane:null,x:Number(point?.x)||null,y:Number(point?.y)||null});}if(children.length)visit(children);}};visit(page?.elements??[]);return nodes;}
const normalizePath=(v:string)=>v.replace(/\\\\/g,"/").replace(/^\/+|\/+$/g,"");
const folderOf=(v:string)=>{const p=normalizePath(v);const i=p.lastIndexOf("/");return i>0?p.slice(0,i):null;};
export class SystemRuleService{
 async summary(){const [p,n,t]=await Promise.all([prisma.$queryRawUnsafe<Array<{c:bigint}>>('SELECT COUNT(*)::bigint c FROM "SystemRuleProcess"'),prisma.$queryRawUnsafe<Array<{c:bigint}>>('SELECT COUNT(*)::bigint c FROM "SystemRuleNode"'),prisma.$queryRawUnsafe<Array<{c:bigint}>>('SELECT COUNT(*)::bigint c FROM "SystemRuleTransition"')]);return{processes:Number(p[0]?.c??0),nodes:Number(n[0]?.c??0),transitions:Number(t[0]?.c??0)};}
 async search(text:string,limit=20){const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").trim();const stop=new Set(["de","da","do","das","dos","e","em","no","na","nos","nas","para","por","com","a","o"]);const q=normalize(text);const terms=q.split(/\s+/).filter(x=>x.length>1&&!stop.has(x));if(!terms.length)return[];const rows=await prisma.$queryRawUnsafe<any[]>('SELECT n.id,n."processId",n.name,n.kind,n.documentation,n.lane,n.x,n.y,p.name "processName",p."sourceFile",p."folderPath" FROM "SystemRuleNode" n JOIN "SystemRuleProcess" p ON p.id=n."processId"');return rows.map(r=>{const name=normalize(String(r.name??"")),process=normalize(String(r.processName??"")),folder=normalize(String(r.folderPath??"")),doc=normalize(String(r.documentation??"")),source=normalize(String(r.sourceFile??""));let matched=0,score=0;for(const term of terms){let best=0;if(name.includes(term))best=40;else if(process.includes(term))best=32;else if(folder.includes(term))best=26;else if(doc.includes(term))best=18;else if(source.includes(term))best=12;if(best){matched++;score+=best;}}if(name===q)score+=100;else if(process.includes(q)||name.includes(q))score+=55;score+=Math.round((matched/terms.length)*50);return{...r,score,matched};}).filter(r=>r.matched>0).sort((a,b)=>b.matched-a.matched||b.score-a.score||a.id-b.id).slice(0,Math.max(1,Math.min(limit,50)));}
 async correlate(text:string,mapItems:any[],limit=12){const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^\p{L}\p{N}_.]+/gu," ").trim();const stop=new Set(["de","da","do","das","dos","e","em","no","na","nos","nas","para","por","com","uma","um","que"]);const baseTerms=normalize(text).split(/\s+/).filter(x=>x.length>2&&!stop.has(x));const ruleItems=await this.search(text,40);const candidates=new Map<number,{item:any;score:number;reasons:Set<string>;terms:Set<string>}>();for(const r of ruleItems){const semantic=[...baseTerms,...normalize(String(r.name??"")+" "+String(r.processName??"")+" "+String(r.documentation??"")).split(/\s+/).filter(x=>x.length>3&&!stop.has(x))].slice(0,24);for(const m of mapItems??[]){const hay=normalize(String(m.nodeText??"")+" "+String(m.path??"")+" "+String(m.mapName??"")+" "+String(m.nodeKind??""));const matched=[...new Set(semantic.filter(t=>hay.includes(t)))];if(!matched.length)continue;const current=candidates.get(m.id)??{item:m,score:Number(m.score??0),reasons:new Set<string>(),terms:new Set<string>()};matched.forEach(t=>current.terms.add(t));if(normalize(String(r.name??"")).split(/\s+/).some(t=>t.length>3&&hay.includes(t)))current.reasons.add("Etapa: "+r.name);if(normalize(String(r.processName??"")).split(/\s+/).some(t=>t.length>3&&hay.includes(t)))current.reasons.add("Fluxo: "+r.processName);current.score+=matched.length*12+Number(r.score??0)/10;candidates.set(m.id,current);}}return[...candidates.values()].sort((a,b)=>b.score-a.score).slice(0,Math.max(1,Math.min(limit,30))).map(x=>({...x.item,correlationScore:Math.round(x.score),correlationTerms:[...x.terms].slice(0,8),reasons:[...x.reasons].slice(0,3)}));}
 async catalog(){const processes=await prisma.$queryRawUnsafe<any[]>(\`SELECT p.id,p.name,p."folderPath",p."sourceFile",(SELECT COUNT(*)::int FROM "SystemRuleNode" n WHERE n."processId"=p.id) steps FROM "SystemRuleProcess" p ORDER BY COALESCE(p."folderPath",''),p.name\`);const tree:any={name:"SIMER (ERP Agronegócio)",type:"raiz",children:{},processes:[]};for(const p of processes){const parts=String(p.folderPath??"").replace(/\\\\/g,"/").split("/").filter(Boolean);let cur=tree;for(const part of parts){cur.children[part]??={name:part,type:"secao",children:{},processes:[]};cur=cur.children[part];}cur.processes.push({id:p.id,name:p.name,sourceFile:p.sourceFile,folderPath:p.folderPath,steps:Number(p.steps??0)});}const convert=(n:any):any=>{const children=Object.values(n.children??{}).map(convert) as any[];const processes=n.processes??[];const total=processes.length+children.reduce((s:number,x:any)=>s+Number(x.total??0),0);return{name:n.name,type:n.type,processes,children,total};};return convert(tree);}
 async relatedProcesses(processId:number,limit=8){return prisma.$queryRawUnsafe<any[]>('SELECT p2.id,p2.name,p2."folderPath",p2."sourceFile",(SELECT COUNT(*)::int FROM "SystemRuleNode" n WHERE n."processId"=p2.id) steps FROM "SystemRuleProcess" p1 JOIN "SystemRuleProcess" p2 ON COALESCE(p2."folderPath",\'\')=COALESCE(p1."folderPath",\'\') AND p2.id<>p1.id WHERE p1.id=$1 ORDER BY p2.name LIMIT $2',processId,limit);}
 async flow(processId:number,focusId?:number){const [process,nodes,transitions]=await Promise.all([prisma.$queryRawUnsafe<any[]>('SELECT * FROM "SystemRuleProcess" WHERE id=$1 LIMIT 1',processId),prisma.$queryRawUnsafe<any[]>('SELECT * FROM "SystemRuleNode" WHERE "processId"=$1 ORDER BY COALESCE(x,0),COALESCE(y,0),id',processId),prisma.$queryRawUnsafe<any[]>('SELECT * FROM "SystemRuleTransition" WHERE "processId"=$1 ORDER BY id',processId)]);return{process:process[0]??null,nodes,transitions,focusId:focusId??null};}
 async importBpm(sourceFile:string,base64:string){sourceFile=normalizePath(sourceFile);let totalNodes=0,totalTransitions=0,processes=0,created=0,updated=0;
  if(sourceFile.toLowerCase().endsWith("configuration.json.js")){const raw=Buffer.from(base64,"base64").toString("utf8");const eq=raw.indexOf("=");if(eq<0)throw new Error("configuration.json.js do Bizagi sem modelo reconhecível.");let model:any;try{model=JSON.parse(raw.slice(eq+1).trim().replace(/;\s*$/,""));}catch{throw new Error("Não foi possível interpretar o configuration.json.js do Bizagi.");}const processFolder=normalizePath(sourceFile.replace(/\/libs\/js\/json\/configuration\.json\.js$/i,""));for(const page of model?.pages??[]){const nodes=parseWebPage(page);if(!nodes.length)continue;const processName=String(page?.name??model?.modelName??processFolder.split("/").pop()??"Processo");const processSource=processFolder+"/bizagi-web";await prisma.$transaction(async tx=>{const old=await tx.$queryRawUnsafe<Array<{id:number}>>('SELECT id FROM "SystemRuleProcess" WHERE LOWER("sourceFile")=LOWER($1) AND LOWER(name)=LOWER($2) LIMIT 1',processSource,processName);let pid=old[0]?.id;if(pid){updated++;await tx.$executeRawUnsafe('DELETE FROM "SystemRuleTransition" WHERE "processId"=$1',pid);await tx.$executeRawUnsafe('DELETE FROM "SystemRuleNode" WHERE "processId"=$1',pid);await tx.$executeRawUnsafe('UPDATE "SystemRuleProcess" SET "folderPath"=$2,"importedAt"=CURRENT_TIMESTAMP WHERE id=$1',pid,processFolder);}else{created++;const ins=await tx.$queryRawUnsafe<Array<{id:number}>>('INSERT INTO "SystemRuleProcess" ("sourceFile",name,"folderPath","importedAt") VALUES ($1,$2,$3,CURRENT_TIMESTAMP) RETURNING id',processSource,processName,processFolder);pid=ins[0]!.id;}for(const n of nodes)await tx.$executeRawUnsafe('INSERT INTO "SystemRuleNode" ("processId","externalId",name,kind,documentation,lane,x,y) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',pid,n.externalId,n.name,n.kind,n.documentation,n.lane,n.x,n.y);});processes++;totalNodes+=nodes.length;}return{sourceFile,format:"bizagi-web-folder",configurations:1,processes,nodes:totalNodes,transitions:0,created,updated};}
  const outer=await JSZip.loadAsync(Buffer.from(base64,"base64"));
  const webConfigs=Object.keys(outer.files).filter(x=>x.toLowerCase().endsWith("configuration.json.js"));
  if(webConfigs.length){for(const configName of webConfigs){const entry=outer.file(configName);if(!entry)continue;const raw=await entry.async("string");const eq=raw.indexOf("=");if(eq<0)continue;let model:any;try{model=JSON.parse(raw.slice(eq+1).trim().replace(/;\s*$/,""));}catch{continue;}const processFolder=normalizePath(configName.replace(/\\/g,"/").replace(/\/libs\/js\/json\/configuration\.json\.js$/i,""));for(const page of model?.pages??[]){const nodes=parseWebPage(page);if(!nodes.length)continue;const processName=String(page?.name??model?.modelName??processFolder.split("/").pop()??"Processo");const processSource=processFolder+"/bizagi-web";await prisma.$transaction(async tx=>{const old=await tx.$queryRawUnsafe<Array<{id:number}>>('SELECT id FROM "SystemRuleProcess" WHERE LOWER("sourceFile")=LOWER($1) AND LOWER(name)=LOWER($2) LIMIT 1',processSource,processName);let pid=old[0]?.id;if(pid){updated++;await tx.$executeRawUnsafe('DELETE FROM "SystemRuleTransition" WHERE "processId"=$1',pid);await tx.$executeRawUnsafe('DELETE FROM "SystemRuleNode" WHERE "processId"=$1',pid);await tx.$executeRawUnsafe('UPDATE "SystemRuleProcess" SET "folderPath"=$2,"importedAt"=CURRENT_TIMESTAMP WHERE id=$1',pid,processFolder);}else{created++;const ins=await tx.$queryRawUnsafe<Array<{id:number}>>('INSERT INTO "SystemRuleProcess" ("sourceFile",name,"folderPath","importedAt") VALUES ($1,$2,$3,CURRENT_TIMESTAMP) RETURNING id',processSource,processName,processFolder);pid=ins[0]!.id;}for(const n of nodes)await tx.$executeRawUnsafe('INSERT INTO "SystemRuleNode" ("processId","externalId",name,kind,documentation,lane,x,y) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',pid,n.externalId,n.name,n.kind,n.documentation,n.lane,n.x,n.y);});processes++;totalNodes+=nodes.length;}}return{sourceFile,format:"bizagi-web",configurations:webConfigs.length,processes,nodes:totalNodes,transitions:0,created,updated};}
  const folderPath=folderOf(sourceFile);
  for(const name of Object.keys(outer.files).filter(x=>x.toLowerCase().endsWith(".diag"))){const diag=await outer.file(name)!.async("nodebuffer");const inner=await JSZip.loadAsync(diag);const entry=inner.file("Diagram.xml");if(!entry)continue;const parsed=parseDiagram(await entry.async("string"),sourceFile);if(!parsed.nodes.length)continue;
   const fileName=sourceFile.replace(/.*[\\/]/,"");
   await prisma.$transaction(async tx=>{const old=await tx.$queryRawUnsafe<Array<{id:number}>>('SELECT id FROM "SystemRuleProcess" WHERE LOWER(name)=LOWER($1) OR LOWER("sourceFile")=LOWER($2) OR LOWER("sourceFile") LIKE LOWER($3) ORDER BY CASE WHEN LOWER(name)=LOWER($1) THEN 0 WHEN LOWER("sourceFile")=LOWER($2) THEN 1 ELSE 2 END LIMIT 1',parsed.processName,sourceFile,"%/"+fileName);let pid=old[0]?.id;if(pid){updated++;await tx.$executeRawUnsafe('DELETE FROM "SystemRuleTransition" WHERE "processId"=$1',pid);await tx.$executeRawUnsafe('DELETE FROM "SystemRuleNode" WHERE "processId"=$1',pid);await tx.$executeRawUnsafe('UPDATE "SystemRuleProcess" SET "sourceFile"=$2,name=$3,"folderPath"=$4,"importedAt"=CURRENT_TIMESTAMP WHERE id=$1',pid,sourceFile,parsed.processName,folderPath);}else{created++;const ins=await tx.$queryRawUnsafe<Array<{id:number}>>('INSERT INTO "SystemRuleProcess" ("sourceFile",name,"folderPath","importedAt") VALUES ($1,$2,$3,CURRENT_TIMESTAMP) RETURNING id',sourceFile,parsed.processName,folderPath);pid=ins[0]!.id;}
    for(const n of parsed.nodes)await tx.$executeRawUnsafe('INSERT INTO "SystemRuleNode" ("processId","externalId",name,kind,documentation,lane,x,y) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',pid,n.externalId,n.name,n.kind,n.documentation,n.lane,n.x,n.y);
    for(const t of parsed.transitions)await tx.$executeRawUnsafe('INSERT INTO "SystemRuleTransition" ("processId","externalId","fromId","toId",name,condition) VALUES ($1,$2,$3,$4,$5,$6)',pid,t.externalId,t.fromId,t.toId,t.name,t.condition);
   });processes++;totalNodes+=parsed.nodes.length;totalTransitions+=parsed.transitions.length;}
  return{sourceFile,processes,nodes:totalNodes,transitions:totalTransitions,created,updated};}
}