import { Router } from "express";
import { SimerMapController } from "../controllers/SimerMapController";
const simerMapRoutes = Router();
const controller = new SimerMapController();
simerMapRoutes.get("/summary", controller.summary);
simerMapRoutes.get("/search", controller.search);
simerMapRoutes.get("/tree", controller.tree);
simerMapRoutes.get("/builder/status", controller.builderStatus);
simerMapRoutes.get("/rules/summary", controller.ruleSummary);
simerMapRoutes.get("/rules/search", controller.ruleSearch);
simerMapRoutes.get("/rules/:processId/flow", controller.ruleFlow);
simerMapRoutes.get("/nodes/:id/container", controller.resolveContainer);
simerMapRoutes.get("/nodes/:id/follow", controller.followLink);
simerMapRoutes.get("/nodes/:id/related", controller.related);
simerMapRoutes.post("/context", controller.context);
simerMapRoutes.post("/rules/import", controller.importRule);
simerMapRoutes.post("/import/batch", controller.importBatch);
simerMapRoutes.post("/import", controller.importMap);
export { simerMapRoutes };
