import { Router } from "express";
import { SimerMapController } from "../controllers/SimerMapController";
const simerMapRoutes = Router();
const controller = new SimerMapController();
simerMapRoutes.get("/summary", controller.summary);
simerMapRoutes.get("/search", controller.search);
simerMapRoutes.get("/builder/status", controller.builderStatus);
simerMapRoutes.get("/nodes/:id/related", controller.related);
simerMapRoutes.post("/context", controller.context);
simerMapRoutes.post("/import/batch", controller.importBatch);
simerMapRoutes.post("/import", controller.importMap);
export { simerMapRoutes };
