import { useEffect,useMemo,useState } from "react";
import { Alert,Box,Button,Card,CardContent,Chip,CircularProgress,Divider,Stack,TextField,Typography } from "@mui/material";
import { AccountTreeOutlined,AnalyticsOutlined,SearchOutlined,TimelineOutlined } from "@mui/icons-material";
import { useNavigate,useSearchParams } from "react-router-dom";
import { api } from "../services/api"; import { PageHeader } from "../components/PageHeader";
type Item={id:string;type:string;title:string;subtitle:string;path:string};
type InvestigationData={ticket:{movideskId:number;subject:string;client?:string;status:string;category?:string;cause?:string;owner?:string};summary:{similarCases:number;relatedWorkItems:number;technicalEvidence?:number;rules?:number;service?:string;version?:string};quality:{score:number;checks:Record<string,boolean>};similar:Array<{movideskId:number;subject:string;client?:string;score:number;reasons:string[]}>;workItems:Array<{id:number;title:string;workItemType:string;state:string}>;timeline:Array<{date:string;kind:string;title:string}>;evidence?:Array<{id:number;title:string;path?:string;mapName?:string;score:number;kind:string}>;ruleItems?:Array<{id?:number;name?:string;nodeText?:string;path?:string}>;anomalies?:string[];diagnosticPlan?:Array<{key:string;title:string;status:"ready"|"attention"|"neutral";detail:string}>;intelligence?:{clientDna:{client?:string|null;totalTickets:number;taskRate:number;topServices:Array<{name:string;total:number}>;topCategories:Array<{name:string;total:number}>;serviceCases:number;periodStart:string;periodEnd:string};recurrence:{strongCases:number;crossClient:boolean;clients:number;concentration:number};versionSignal?:{version:string;cases:number;text:string}|null;signals:Array<{severity:"info"|"warning"|"success";title:string;detail:string}>;confidence:{score:number;basis:string[]}}};
export function Investigation(){const navigate=useNavigate();const [params,setParams]=useSearchParams();const [query,setQuery]=useState(params.get("q")??"");const [items,setItems]=useState<Item[]>([]);const [data,setData]=useState<InvestigationData|null>(null);const [loading,setLoading]=useState(false);
const run=async(value=query)=>{const q=value.trim();if(q.length<2)return;setLoading(true);setData(null);try{const numeric=Number(q.replace(/^#/,""));if(Number.isSafeInteger(numeric)){const r=await api.get<InvestigationData>("/global/investigate",{params:{q}});setData(r.data);setItems([]);}else{const r=await api.get<{items:Item[]}>("/global/search",{params:{q}});setItems(r.data.items);}setParams({q});}finally{setLoading(false)}};
useEffect(()=>{if(query.trim().length>=2)void run(query)},[]);const grouped=useMemo(()=>items.reduce<Record<string,Item[]>>((a,i)=>{(a[i.type]??=[]).push(i);return a},{}),[items]);
return <Box><PageHeader eyebrow="INTELIGÊNCIA" title="Central de Investigação" description="Cruze atendimento, Azure, cliente, versão, regra e conhecimento em um único workspace."/><Card variant="outlined" sx={{mb:2,background:t=>t.palette.mode==="dark"?"linear-gradient(135deg,rgba(16,42,67,.9),rgba(18,30,55,.82))":undefined}}><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField fullWidth value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void run()}} placeholder="Ticket, erro, cliente, serviço, rotina, versão ou Task Azure..." slotProps={{input:{startAdornment:<SearchOutlined sx={{mr:1,color:"text.secondary"}}/>}}}/><Button variant="contained" onClick={()=>void run()} disabled={loading}>{loading?<CircularProgress size={20}/>:"Investigar"}</Button></Stack></CardContent></Card>{!items.length&&!data&&!loading&&<Alert severity="info">Informe um número de atendimento para montar o dossiê técnico, ou pesquise por cliente, serviço, rotina, versão ou Task Azure.</Alert>}
{data&&<Stack spacing={2}>
<Card variant="outlined"><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{justifyContent:"space-between"}}><Box><Typography variant="overline" color="text.secondary">DOSSIÊ TÉCNICO</Typography><Typography variant="h5" sx={{fontWeight:900}}>#{data.ticket.movideskId} · {data.ticket.subject}</Typography><Typography color="text.secondary">{[data.ticket.client,data.ticket.status,data.ticket.owner].filter(Boolean).join(" · ")}</Typography></Box><Stack direction="row" spacing={1} sx={{flexWrap:"wrap",alignContent:"flex-start"}}><Chip label={`Qualidade ${data.quality.score}%`} color={data.quality.score>=80?"success":"warning"}/><Chip label={`${data.summary.similarCases} similares`}/><Chip label={`${data.summary.relatedWorkItems} Azure`}/><Chip label={`${data.summary.technicalEvidence??0} evidências`}/><Chip label={`${data.summary.rules??0} regras`}/></Stack></Stack></CardContent></Card>
<Stack direction={{xs:"column",lg:"row"}} spacing={2}>
<Card variant="outlined" sx={{flex:1}}><CardContent><Typography sx={{fontWeight:850,mb:1}}>Contexto técnico</Typography>{[["Cliente",data.ticket.client],["Categoria",data.ticket.category],["Causa",data.ticket.cause],["Serviço",data.summary.service],["Versão",data.summary.version]].map(([k,v])=><Box key={k} sx={{display:"flex",justifyContent:"space-between",gap:2,py:.6}}><Typography color="text.secondary">{k}</Typography><Typography sx={{fontWeight:700,textAlign:"right"}}>{v||"—"}</Typography></Box>)}</CardContent></Card>
<Card variant="outlined" sx={{flex:1}}><CardContent><Typography sx={{fontWeight:850,mb:1}}>Qualidade dos dados</Typography>{Object.entries(data.quality.checks).map(([k,v])=><Stack key={k} direction="row" spacing={1} sx={{alignItems:"center",py:.45}}><Chip size="small" color={v?"success":"default"} label={v?"OK":"Pendente"}/><Typography>{k}</Typography></Stack>)}</CardContent></Card>
</Stack>
{Boolean(data.diagnosticPlan?.length)&&<Card variant="outlined"><CardContent><Typography sx={{fontWeight:850,mb:.25}}>Plano de investigação</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1.25}}>Sequência auditável de verificações. O sistema apresenta evidências; a conclusão técnica permanece com o analista.</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)",xl:"repeat(5,1fr)"},gap:1}}>{data.diagnosticPlan!.map((step,index)=><Box key={step.key} sx={{p:1.25,border:"1px solid",borderColor:step.status==="attention"?"warning.main":"divider",borderRadius:2,bgcolor:"background.paper"}}><Stack direction="row" spacing={.7} sx={{alignItems:"center",mb:.6}}><Chip size="small" color={step.status==="ready"?"success":step.status==="attention"?"warning":"default"} label={index+1}/><Typography sx={{fontWeight:800}}>{step.title}</Typography></Stack><Typography variant="caption" color="text.secondary">{step.detail}</Typography></Box>)}</Box></CardContent></Card>}
{data.intelligence&&<><Card variant="outlined"><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{justifyContent:"space-between",alignItems:{md:"center"},mb:1.5}}><Box><Typography sx={{fontWeight:850}}>Inteligência de recorrência</Typography><Typography variant="body2" color="text.secondary">Sinais determinísticos baseados no histórico local. Associação não implica causalidade.</Typography></Box><Chip color={data.intelligence.confidence.score>=75?"success":data.intelligence.confidence.score>=50?"warning":"default"} label={`Confiança dos dados · ${data.intelligence.confidence.score}%`}/></Stack><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(4,1fr)"},gap:1}}>{[["Casos fortes",data.intelligence.recurrence.strongCases],["Clientes no padrão",data.intelligence.recurrence.clients],["Concentração no cliente",`${data.intelligence.recurrence.concentration}%`],["Versão recorrente",data.intelligence.versionSignal?.version??"—"]].map(([label,value])=><Box key={label} sx={{p:1.25,border:"1px solid",borderColor:"divider",borderRadius:2}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" sx={{fontWeight:900}}>{value}</Typography></Box>)}</Box><Stack spacing={1} sx={{mt:1.5}}>{data.intelligence.signals.map((x,i)=><Alert key={i} severity={x.severity}><Typography sx={{fontWeight:800}}>{x.title}</Typography><Typography variant="body2">{x.detail}</Typography></Alert>)}</Stack></CardContent></Card>
<Card variant="outlined"><CardContent><Typography sx={{fontWeight:850}}>DNA Técnico do Cliente</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1.5}}>Perfil do histórico próximo ao atendimento investigado; serve para contexto, não para atribuição automática de causa.</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"1fr 1fr"},gap:2}}><Box><Stack direction="row" spacing={1} useFlexGap sx={{flexWrap:"wrap",mb:1}}><Chip label={`${data.intelligence.clientDna.totalTickets} tickets no recorte`}/><Chip label={`${data.intelligence.clientDna.taskRate}% com Task`}/><Chip label={`${data.intelligence.clientDna.serviceCases} no serviço atual`}/></Stack><Typography variant="caption" color="text.secondary">Serviços mais frequentes</Typography>{data.intelligence.clientDna.topServices.map(x=><Box key={x.name} sx={{display:"flex",justifyContent:"space-between",py:.45}}><Typography variant="body2">{x.name}</Typography><Chip size="small" variant="outlined" label={x.total}/></Box>)}</Box><Box><Typography variant="caption" color="text.secondary">Categorias mais frequentes</Typography>{data.intelligence.clientDna.topCategories.map(x=><Box key={x.name} sx={{display:"flex",justifyContent:"space-between",py:.45}}><Typography variant="body2">{x.name}</Typography><Chip size="small" variant="outlined" label={x.total}/></Box>)}</Box></Box></CardContent></Card></>}
{Boolean(data.anomalies?.length)&&<Alert severity="warning"><Typography sx={{fontWeight:800,mb:.5}}>Sinais para investigação</Typography>{data.anomalies!.map((x,i)=><Typography key={i} variant="body2">• {x}</Typography>)}</Alert>}
<Stack direction={{xs:"column",lg:"row"}} spacing={2}>
<Card variant="outlined" sx={{flex:1}}><CardContent><Typography sx={{fontWeight:850,mb:1}}>Regra × evidência</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1}}>Pontos técnicos encontrados automaticamente no Mapa SIMER e confrontados com o contexto do atendimento.</Typography>{data.evidence?.length?data.evidence.map(x=><Box key={x.id} onClick={()=>navigate(`/mapa-simer?focusId=${x.id}`)} sx={{p:1,borderRadius:2,cursor:"pointer","&:hover":{bgcolor:"action.hover"}}}><Stack direction="row" spacing={1} sx={{alignItems:"center"}}><Chip size="small" label={x.kind}/><Chip size="small" variant="outlined" label={`${x.score} pts`}/><Typography sx={{fontWeight:700}}>{x.title}</Typography></Stack><Typography variant="caption" color="text.secondary">{[x.mapName,x.path].filter(Boolean).join(" · ")}</Typography></Box>):<Alert severity="info">Nenhuma evidência técnica correlacionada.</Alert>}</CardContent></Card>
<Card variant="outlined" sx={{flex:1}}><CardContent><Typography sx={{fontWeight:850,mb:1}}>Regras do Sistema relacionadas</Typography>{data.ruleItems?.length?data.ruleItems.slice(0,8).map((x,i)=><Box key={x.id??i} sx={{py:.7}}><Typography sx={{fontWeight:700}}>{x.name??x.nodeText??"Regra relacionada"}</Typography><Typography variant="caption" color="text.secondary">{x.path??""}</Typography></Box>):<Alert severity="info">Nenhuma regra BPMN relacionada ao contexto.</Alert>}</CardContent></Card>
</Stack>
<Card variant="outlined"><CardContent><Typography sx={{fontWeight:850}}>Casos semelhantes</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1}}>Score explicável por cliente, serviço, categoria, causa, versão e termos do assunto.</Typography>{data.similar.length?data.similar.map(x=><Box key={x.movideskId} onClick={()=>navigate(`/tickets?movidesk=${x.movideskId}`)} sx={{p:1.2,borderRadius:2,cursor:"pointer","&:hover":{bgcolor:"action.hover"}}}><Stack direction="row" spacing={1} sx={{alignItems:"center"}}><Chip size="small" label={`${x.score} pts`}/><Typography sx={{fontWeight:750}}>#{x.movideskId} · {x.subject}</Typography></Stack><Typography variant="caption" color="text.secondary">{[x.client,...x.reasons].filter(Boolean).join(" · ")}</Typography></Box>):<Alert severity="info">Nenhum caso com correlação mínima encontrado.</Alert>}</CardContent></Card>
<Stack direction={{xs:"column",lg:"row"}} spacing={2}><Card variant="outlined" sx={{flex:1}}><CardContent><Typography sx={{fontWeight:850,mb:1}}>Azure relacionado</Typography>{data.workItems.map(x=><Box key={x.id} sx={{py:.7}}><Typography sx={{fontWeight:700}}>#{x.id} · {x.title}</Typography><Typography variant="caption" color="text.secondary">{x.workItemType} · {x.state}</Typography></Box>)}</CardContent></Card><Card variant="outlined" sx={{flex:1}}><CardContent><Typography sx={{fontWeight:850,mb:1}}>O que mudou?</Typography>{data.timeline.map((x,i)=><Box key={i} sx={{borderLeft:"2px solid",borderColor:"divider",pl:1.5,pb:1}}><Typography sx={{fontWeight:700}}>{x.title}</Typography><Typography variant="caption" color="text.secondary">{new Date(x.date).toLocaleString("pt-BR")}</Typography></Box>)}</CardContent></Card></Stack>
</Stack>}<Stack spacing={2}>{Object.entries(grouped).map(([type,list])=><Card key={type} variant="outlined"><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><AnalyticsOutlined fontSize="small"/><Typography sx={{fontWeight:850}}>{type}</Typography><Chip size="small" label={list.length}/></Stack><Divider sx={{mb:1}}/>{list.slice(0,8).map(i=><Box key={i.id} onClick={()=>navigate(i.path)} sx={{p:1.2,borderRadius:2,cursor:"pointer","&:hover":{bgcolor:"action.hover"}}}><Typography sx={{fontWeight:750}}>{i.title}</Typography><Typography variant="caption" color="text.secondary">{i.subtitle}</Typography></Box>)}</CardContent></Card>)}</Stack><Card variant="outlined" sx={{mt:2}}><CardContent><Typography sx={{fontWeight:850}}>Inteligência de diagnóstico</Typography><Stack direction="row" useFlexGap sx={{flexWrap:"wrap",gap:1,mt:1}}><Chip icon={<AccountTreeOutlined/>} label="Regra × evidência"/><Chip icon={<TimelineOutlined/>} label="O que mudou?"/><Chip label="Casos semelhantes"/><Chip label="Anomalias"/><Chip label="SQL diagnóstico"/></Stack></CardContent></Card></Box>}
