import { useEffect,useMemo,useState } from "react";
import { Alert,Box,Button,Card,CardContent,Chip,CircularProgress,Divider,Stack,TextField,Typography } from "@mui/material";
import { AccountTreeOutlined,AnalyticsOutlined,SearchOutlined,TimelineOutlined } from "@mui/icons-material";
import { useNavigate,useSearchParams } from "react-router-dom";
import { api } from "../services/api"; import { PageHeader } from "../components/PageHeader";
type Item={id:string;type:string;title:string;subtitle:string;path:string};
export function Investigation(){const navigate=useNavigate();const [params,setParams]=useSearchParams();const [query,setQuery]=useState(params.get("q")??"");const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(false);
const run=async(value=query)=>{const q=value.trim();if(q.length<2)return;setLoading(true);try{const r=await api.get<{items:Item[]}>("/global/search",{params:{q}});setItems(r.data.items);setParams({q});}finally{setLoading(false)}};
useEffect(()=>{if(query.trim().length>=2)void run(query)},[]);const grouped=useMemo(()=>items.reduce<Record<string,Item[]>>((a,i)=>{(a[i.type]??=[]).push(i);return a},{}),[items]);
return <Box><PageHeader title="Central de Investigação" subtitle="Cruze atendimento, Azure, cliente, versão, regra e conhecimento em um único workspace."/><Card variant="outlined" sx={{mb:2,background:t=>t.palette.mode==="dark"?"linear-gradient(135deg,rgba(16,42,67,.9),rgba(18,30,55,.82))":undefined}}><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField fullWidth value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void run()}} placeholder="Ticket, erro, cliente, serviço, rotina, versão ou Task Azure..." InputProps={{startAdornment:<SearchOutlined sx={{mr:1,color:"text.secondary"}}/>}}/><Button variant="contained" onClick={()=>void run()} disabled={loading}>{loading?<CircularProgress size={20}/>:"Investigar"}</Button></Stack></CardContent></Card>{!items.length&&!loading&&<Alert severity="info">Informe um contexto para montar a investigação. A busca correlaciona as fontes já disponíveis no TechLead Hub.</Alert>}<Stack spacing={2}>{Object.entries(grouped).map(([type,list])=><Card key={type} variant="outlined"><CardContent><Stack direction="row" spacing={1} alignItems="center" mb={1}><AnalyticsOutlined fontSize="small"/><Typography fontWeight={850}>{type}</Typography><Chip size="small" label={list.length}/></Stack><Divider sx={{mb:1}}/>{list.slice(0,8).map(i=><Box key={i.id} onClick={()=>navigate(i.path)} sx={{p:1.2,borderRadius:2,cursor:"pointer","&:hover":{bgcolor:"action.hover"}}}><Typography fontWeight={750}>{i.title}</Typography><Typography variant="caption" color="text.secondary">{i.subtitle}</Typography></Box>)}</CardContent></Card>)}</Stack><Card variant="outlined" sx={{mt:2}}><CardContent><Typography fontWeight={850}>Inteligência de diagnóstico</Typography><Stack direction="row" useFlexGap flexWrap="wrap" gap={1} mt={1}><Chip icon={<AccountTreeOutlined/>} label="Regra × evidência"/><Chip icon={<TimelineOutlined/>} label="O que mudou?"/><Chip label="Casos semelhantes"/><Chip label="Anomalias"/><Chip label="SQL diagnóstico"/></Stack></CardContent></Card></Box>}
