import { AddRounded, CampaignOutlined, EditOutlined, PushPinOutlined, SearchRounded, VisibilityOutlined } from "@mui/icons-material";
import { Alert, Autocomplete, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, MenuItem, Stack, Switch, TextField, Typography, useTheme } from "@mui/material";
import { useCallback, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { SectionInfo } from "../components/SectionInfo";
import { api, getApiErrorMessage } from "../services/api";
import { aliareColors } from "../theme/theme";

type Problem={id:number;title:string;symptom:string;solution:string;cause:string|null;workaround:string|null;technicalSolution:string|null;comment:string|null;azureWorkItemType:string|null;azureUrl:string|null;service:string|null;client:string|null;movideskTicket:string|null;azureWorkItem:string|null;version:string|null;status:string;severity:string;tags:string|null;pinned:boolean;updatedAt:string;updatedByName:string|null;readCount:number};
type Source={kind:"ticket"|"workItem";id:number;label:string;subject:string;client:string;service:string;version:string;criticality?:string;movidesk?:number|null;cause?:string;workaround?:string;technicalSolution?:string;workItemType?:string;url?:string};
type TechnicalDna={service:string;periodDays:number;totalTickets:number;recent30:number;previous30:number;trendPct:number;clients:Array<{name:string;total:number}>;causes:Array<{name:string;total:number}>;categories:Array<{name:string;total:number}>;versions:Array<{name:string;total:number}>;analysts:Array<{name:string;total:number}>;development:{linkedTickets:number;workItems:number;solutions:Array<{id:number;title:string;type:string;state:string;workaround?:string|null;technicalSolution?:string|null;version?:string|null}>};knownProblems:Array<{id:number;title:string;status:string;severity:string}>;confidence:{score:number;basis:string[]};sampleTickets:Array<{movideskId:number;subject:string;client?:string|null;owner?:string|null}>};
type Candidate={service:string;category:string;cause:string;version:string;cases:number;clients:number;tickets:number[];tasks:number[];sampleSubjects:string[];covered:boolean;priority:"high"|"medium"|"review";score:number;recent30:number;previous30:number;trendPct:number;topTerms:string[];linkedTaskCount:number};
type Form={title:string;symptom:string;solution:string;cause:string;workaround:string;technicalSolution:string;comment:string;azureWorkItemType:string;azureUrl:string;service:string;client:string;movideskTicket:string;azureWorkItem:string;version:string;status:string;severity:string;tags:string;pinned:boolean};
const empty:Form={title:"",symptom:"",solution:"",cause:"",workaround:"",technicalSolution:"",comment:"",azureWorkItemType:"",azureUrl:"",service:"",client:"",movideskTicket:"",azureWorkItem:"",version:"",status:"ATIVO",severity:"MEDIA",tags:"",pinned:false};
const statusLabel:Record<string,string>={ATIVO:"Ativo",INVESTIGANDO:"Em investigação",CORRECAO_ANDAMENTO:"Correção em andamento",RESOLVIDO:"Resolvido"};
const plain=(value?:string)=>value?value.replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim():"";
const severityColor:Record<string,"default"|"info"|"warning"|"error">={BAIXA:"default",MEDIA:"info",ALTA:"warning",CRITICA:"error"};

export function KnownProblems(){
 const navigate=useNavigate(); const [searchParams,setSearchParams]=useSearchParams();
 const theme=useTheme(),[candidates,setCandidates]=useState<Candidate[]>([]),[sourceQuery,setSourceQuery]=useState(""),[sources,setSources]=useState<Source[]>([]),[sourceLoading,setSourceLoading]=useState(false),[items,setItems]=useState<Problem[]>([]),[unread,setUnread]=useState(0),[q,setQ]=useState(searchParams.get("q")??""),[status,setStatus]=useState(""),[severity,setSeverity]=useState(""),[view,setView]=useState<"all"|"active"|"critical"|"pinned">("all"),[open,setOpen]=useState(false),[editing,setEditing]=useState<number|null>(null),[form,setForm]=useState<Form>(empty),[error,setError]=useState(""),[saving,setSaving]=useState(false),[dna,setDna]=useState<TechnicalDna|null>(null),[dnaLoading,setDnaLoading]=useState(false),[focusedProblem,setFocusedProblem]=useState<number|null>(null);
 const load=useCallback(async()=>{try{const r=await api.get<{items:Problem[];unread:number}>("/known-problems",{params:{q:q||undefined,status:status||undefined}});setItems(r.data.items);setUnread(r.data.unread);}catch(e:unknown){setError(getApiErrorMessage(e,"Não foi possível atualizar o quadro."))}},[q,status]);
 useEffect(()=>{if(sourceQuery.trim().length<2){setSources([]);return}const t=window.setTimeout(async()=>{try{setSourceLoading(true);const r=await api.get<any>("/known-problems/sources",{params:{q:sourceQuery}});const tickets:Source[]=r.data.tickets.map((x:any)=>({kind:"ticket",id:x.movideskId,label:`Ticket #${x.movideskId} · ${x.subject}`,subject:x.subject,client:x.client??"",service:[x.serviceFirstLevel,x.serviceSecondLevel,x.serviceThirdLevel].filter(Boolean).join(" › "),version:x.deliveredVersion??x.registeredVersion??"",movidesk:x.movideskId,cause:x.causeDetail??x.cause??"",workItemType:x.taskType??"",url:x.taskUrl??""}));const workItems:Source[]=r.data.workItems.map((x:any)=>({kind:"workItem",id:x.id,label:`${x.workItemType} #${x.id} · ${x.title}`,subject:x.title,client:x.client??"",service:[x.module,x.process].filter(Boolean).join(" › "),version:x.deliveredVersion??x.registeredVersion??"",criticality:x.criticality??"",movidesk:x.movideskTicket,cause:x.reason??"",workaround:x.workaround??"",technicalSolution:x.technicalSolution??"",workItemType:x.workItemType??"",url:x.remoteUrl??""}));setSources([...tickets,...workItems])}catch{setSources([])}finally{setSourceLoading(false)}},280);return()=>window.clearTimeout(t)},[sourceQuery]);
 function applySource(x:Source|null){if(!x)return;const severity=x.criticality?.toLocaleUpperCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g,"");setForm(v=>({...v,title:x.subject,client:x.client||v.client,service:x.service||v.service,version:x.version||v.version,movideskTicket:x.movidesk?String(x.movidesk):v.movideskTicket,azureWorkItem:x.kind==="workItem"?String(x.id):v.azureWorkItem,cause:plain(x.cause)||v.cause,workaround:plain(x.workaround)||v.workaround,technicalSolution:plain(x.technicalSolution)||v.technicalSolution,solution:plain(x.technicalSolution)||plain(x.workaround)||v.solution,azureWorkItemType:x.workItemType||v.azureWorkItemType,azureUrl:x.url||v.azureUrl,severity:["BAIXA","MEDIA","ALTA","CRITICA"].includes(severity??"")?severity!:v.severity}));}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(t)},[load]);
 useEffect(()=>{
   const problemId=Number(searchParams.get("problem"));
   if(!Number.isSafeInteger(problemId)||problemId<=0)return;

   if(q||status||severity||view!=="all"){
     setQ("");setStatus("");setSeverity("");setView("all");
     return;
   }

   if(!items.length)return;
   const target=items.find(item=>item.id===problemId);
   if(!target)return;

   setFocusedProblem(problemId);
   const scrollTimer=window.setTimeout(()=>document.getElementById(`known-problem-${problemId}`)?.scrollIntoView({behavior:"smooth",block:"center"}),120);
   const clearTimer=window.setTimeout(()=>setFocusedProblem(current=>current===problemId?null:current),5000);
   const next=new URLSearchParams(searchParams);next.delete("problem");setSearchParams(next,{replace:true});
   return()=>{window.clearTimeout(scrollTimer);window.clearTimeout(clearTimer)};
 },[items,searchParams,setSearchParams,q,status,severity,view]);
 useEffect(()=>{api.get<{items:Candidate[]}>("/known-problems/candidates").then(r=>setCandidates(r.data.items)).catch(()=>setCandidates([]));},[items.length]);
 async function loadDna(service:string){try{setDnaLoading(true);const r=await api.get<TechnicalDna>("/known-problems/technical-dna",{params:{service}});setDna(r.data)}catch(e:unknown){setError(getApiErrorMessage(e,"Não foi possível consolidar o DNA Técnico."))}finally{setDnaLoading(false)}}
 function edit(item?:Problem){setSourceQuery("");setSources([]);if(item){setEditing(item.id);setForm({title:item.title,symptom:item.symptom,solution:item.solution,cause:item.cause??"",workaround:item.workaround??"",technicalSolution:item.technicalSolution??"",comment:item.comment??"",azureWorkItemType:item.azureWorkItemType??"",azureUrl:item.azureUrl??"",service:item.service??"",client:item.client??"",movideskTicket:item.movideskTicket??"",azureWorkItem:item.azureWorkItem??"",version:item.version??"",status:item.status,severity:item.severity,tags:item.tags??"",pinned:item.pinned})}else{setEditing(null);setForm(empty)}setOpen(true)}
 async function syncReference(kind:"ticket"|"workItem",value:string){const id=Number(value);if(!Number.isInteger(id)||id<=0)return;try{const r=await api.get<any>("/known-problems/sources",{params:{q:String(id)}});const raw=kind==="ticket"?r.data.tickets.find((x:any)=>x.movideskId===id):r.data.workItems.find((x:any)=>x.id===id);if(!raw)return;const source:Source=kind==="ticket"?{kind,id:raw.movideskId,label:"",subject:raw.subject,client:raw.client??"",service:[raw.serviceFirstLevel,raw.serviceSecondLevel,raw.serviceThirdLevel].filter(Boolean).join(" › "),version:raw.deliveredVersion??raw.registeredVersion??"",movidesk:raw.movideskId,cause:raw.causeDetail??raw.cause??"",workItemType:raw.taskType??"",url:raw.taskUrl??""}:{kind,id:raw.id,label:"",subject:raw.title,client:raw.client??"",service:[raw.module,raw.process].filter(Boolean).join(" › "),version:raw.deliveredVersion??raw.registeredVersion??"",criticality:raw.criticality??"",movidesk:raw.movideskTicket,cause:raw.reason??"",workaround:raw.workaround??"",technicalSolution:raw.technicalSolution??"",workItemType:raw.workItemType??"",url:raw.remoteUrl??""};applySource(source)}catch{}}
 function openAzure(item:Problem){const type=(item.azureWorkItemType??"").toLocaleLowerCase("pt-BR");const route=type.includes("evolu")?"/evolucoes":type.includes("apoio")?"/apoios":"/correcoes";navigate(route+"?task="+item.azureWorkItem)}
 async function save(){try{setSaving(true);setError("");if(editing)await api.put(`/known-problems/${editing}`,form);else await api.post("/known-problems",form);setOpen(false);setSourceQuery("");setSources([]);await load();}catch(e:unknown){setError(getApiErrorMessage(e,"Não foi possível salvar."))}finally{setSaving(false)}}
 async function read(id:number){await api.post(`/known-problems/${id}/read`);setUnread(v=>Math.max(0,v-1))}
 const active=items.filter(x=>x.status!=="RESOLVIDO").length,critical=items.filter(x=>x.severity==="CRITICA"&&x.status!=="RESOLVIDO").length;
 const visibleItems=items.filter(x=>(!severity||x.severity===severity)&&(view==="all"||(view==="active"&&x.status!=="RESOLVIDO")||(view==="critical"&&x.severity==="CRITICA"&&x.status!=="RESOLVIDO")||(view==="pinned"&&x.pinned)));
 return <Box sx={{pb:4}}>
  <PageHeader eyebrow="Inteligência colaborativa" title="Problemas Conhecidos" description="Radar operacional compartilhado para N1/N2: identifique sintomas, aplique paliativos e acompanhe Correções, Evoluções e APOIOs em um único lugar." meta={`${active} ativo(s) · ${unread} atualização(ões) para ler · sincronização automática a cada 10s`} action={<Button variant="contained" startIcon={<AddRounded/>} onClick={()=>edit()}>Nova publicação</Button>}/>
  {error&&<Alert severity="error" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}
  <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",sm:"repeat(2,minmax(0,1fr))",xl:"repeat(3,minmax(0,1fr))"},gap:1.25,mb:2}}>
   {[["Radar ativo",active,"Casos disponíveis para atuação",aliareColors.green,"Publicações que ainda não estão resolvidas."],["Críticos",critical,"Prioridade máxima do time",aliareColors.error,"Problemas com criticidade CRÍTICA e ainda ativos."],["Não lidos",unread,"Alterações desde sua última leitura",aliareColors.info,"Atualizações que ainda não foram marcadas como lidas por você."]].map(([label,value,sub,color,info])=><Card key={String(label)} variant="outlined" sx={{background:theme.palette.mode==="dark"?"radial-gradient(circle at 10% 0%,rgba(24,199,122,.07),transparent 42%),linear-gradient(135deg,rgba(12,36,57,.96),rgba(14,28,50,.94))":"linear-gradient(135deg,#fff,#f6fbfa)",borderTop:`2px solid ${color}`,transition:"transform .18s ease,box-shadow .18s ease","&:hover":{transform:"translateY(-2px)",boxShadow:theme.palette.mode==="dark"?"0 14px 30px rgba(0,0,0,.2)":"0 12px 26px rgba(15,23,42,.07)"}}}><CardContent sx={{p:1.6,"&:last-child":{pb:1.6}}}><Stack direction="row" sx={{alignItems:"center"}}><Typography variant="caption" color="text.secondary" sx={{fontWeight:800,textTransform:"uppercase",letterSpacing:".08em"}}>{label}</Typography><SectionInfo title={String(info)}/></Stack><Typography sx={{fontSize:"1.85rem",fontWeight:900,lineHeight:1.1,mt:.45}}>{value}</Typography><Typography variant="body2" color="text.secondary">{sub}</Typography></CardContent></Card>)}
  </Box>
  {candidates.length>0&&<Card variant="outlined" sx={{mb:2,borderColor:"rgba(245,158,11,.28)",background:theme.palette.mode==="dark"?"linear-gradient(135deg,rgba(55,36,12,.24),rgba(14,28,50,.94))":"linear-gradient(135deg,#fffaf0,#fff)"}}><CardContent><Stack direction={{xs:"column",md:"row"}} sx={{justifyContent:"space-between",gap:1,mb:1.2}}><Box><Typography sx={{fontWeight:900}}>Candidatos detectados automaticamente</Typography><Typography variant="body2" color="text.secondary">Correlação automática por rotina, categoria, causa, clientes, tendência e vínculo com desenvolvimento. A publicação continua exigindo revisão humana.</Typography></Box><Chip color="warning" label={`${candidates.length} para revisar`}/></Stack><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"repeat(2,minmax(0,1fr))"},gap:1}}>{candidates.slice(0,6).map((x,i)=><Box key={i} sx={{p:1.2,border:"1px solid",borderColor:"divider",borderRadius:2,bgcolor:"background.paper"}}><Stack direction="row" spacing={.6} useFlexGap sx={{alignItems:"center",flexWrap:"wrap"}}><Chip size="small" color={x.priority==="high"?"error":"warning"} label={x.priority==="high"?"Alta recorrência":"Revisar"}/><Typography sx={{fontWeight:850,flex:1}}>{x.service}</Typography><Chip size="small" variant="outlined" label={`${x.cases} casos`}/><Chip size="small" variant="outlined" label={`${x.clients} clientes`}/></Stack><Stack direction="row" spacing={.6} useFlexGap sx={{mt:.6,flexWrap:"wrap"}}><Chip size="small" variant="outlined" label={`Score ${x.score}/100`}/><Chip size="small" variant="outlined" label={`${x.recent30} em 30d`}/>{x.trendPct!==0&&<Chip size="small" color={x.trendPct>0?"warning":"success"} variant="outlined" label={`${x.trendPct>0?"+":""}${x.trendPct}% vs. 30d anteriores`}/>} {x.linkedTaskCount>0&&<Chip size="small" variant="outlined" label={`${x.linkedTaskCount} vínculo(s) Azure`}/>}</Stack><Typography variant="caption" color="text.secondary">{x.category} · {x.cause} · {x.version}</Typography><Typography variant="body2" sx={{mt:.7}}>{x.sampleSubjects[0]??"Sem assunto de referência"}</Typography>{x.topTerms.length>0&&<Typography variant="caption" color="text.secondary" sx={{display:"block",mt:.45}}>Sinais recorrentes: {x.topTerms.join(" · ")}</Typography>}<Stack direction="row" spacing={.75} useFlexGap sx={{mt:1,flexWrap:"wrap"}}><Button size="small" onClick={()=>navigate(`/investigacao?q=${encodeURIComponent(x.service+" "+x.category)}`)}>Investigar</Button><Button size="small" onClick={()=>void loadDna(x.service)} disabled={dnaLoading}>DNA Técnico</Button><Button size="small" variant="outlined" onClick={()=>{setSourceQuery(String(x.tickets[0]??""));setEditing(null);setForm({...empty,title:x.sampleSubjects[0]??x.service,service:x.service,version:x.version,movideskTicket:String(x.tickets[0]??""),azureWorkItem:String(x.tasks[0]??"")});setOpen(true)}}>Revisar publicação</Button></Stack></Box>)}</Box></CardContent></Card>}
  {dna&&<Card variant="outlined" sx={{mb:2,borderColor:"rgba(24,199,122,.25)"}}><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={1} sx={{justifyContent:"space-between",alignItems:{md:"center"},mb:1.2}}><Box><Typography sx={{fontWeight:900}}>DNA Técnico · {dna.service}</Typography><Typography variant="body2" color="text.secondary">Histórico consolidado dos últimos {dna.periodDays} dias: causas, clientes, experiência, desenvolvimento e conhecimento existente.</Typography></Box><Stack direction="row" spacing={.6}><Chip color={dna.confidence.score>=75?"success":dna.confidence.score>=50?"warning":"default"} label={`Confiança ${dna.confidence.score}%`}/><Button size="small" onClick={()=>setDna(null)}>Fechar</Button></Stack></Stack><Box sx={{display:"grid",gridTemplateColumns:{xs:"repeat(2,1fr)",md:"repeat(4,1fr)"},gap:1,mb:1.4}}>{[["Tickets",dna.totalTickets],["Últimos 30d",dna.recent30],["Vínculos Azure",dna.development.linkedTickets],["Problemas conhecidos",dna.knownProblems.length]].map(([label,value])=><Box key={String(label)} sx={{p:1.1,border:"1px solid",borderColor:"divider",borderRadius:2}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" sx={{fontWeight:900}}>{value}</Typography></Box>)}</Box><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"repeat(3,1fr)"},gap:1.2}}>{[["Causas predominantes",dna.causes],["Clientes afetados",dna.clients],["Experiência por analista",dna.analysts]].map(([title,rows])=><Box key={String(title)} sx={{p:1.2,border:"1px solid",borderColor:"divider",borderRadius:2}}><Typography sx={{fontWeight:850,mb:.7}}>{String(title)}</Typography>{(rows as Array<{name:string;total:number}>).slice(0,5).map((row,index)=><Stack key={`${row.name}-${index}`} direction="row" sx={{justifyContent:"space-between",gap:1,py:.35}}><Typography variant="body2" noWrap>{row.name}</Typography><Chip size="small" variant="outlined" label={row.total}/></Stack>)}</Box>)}</Box>{dna.development.solutions.length>0&&<Alert severity="info" sx={{mt:1.2}}><Typography sx={{fontWeight:850}}>Conhecimento de desenvolvimento disponível</Typography><Typography variant="body2">{dna.development.solutions.length} Correção/Evolução/APOIO possui paliativo ou solução técnica registrada para este contexto.</Typography></Alert>}<Stack direction="row" spacing={1} sx={{mt:1.2}}><Button size="small" variant="outlined" onClick={()=>navigate(`/investigacao?q=${encodeURIComponent(dna.service)}`)}>Abrir investigação completa</Button></Stack></CardContent></Card>}
  <Card variant="outlined" sx={{mb:2,borderColor:t=>t.palette.mode==="dark"?"rgba(66,230,193,.16)":"rgba(15,118,110,.12)"}}><CardContent sx={{p:1.5,"&:last-child":{pb:1.5}}}><Stack direction="row" sx={{alignItems:"center",mb:1}}><Box><Typography sx={{fontWeight:900}}>Explorar conhecimento operacional</Typography><Typography variant="caption" color="text.secondary">Pesquise, filtre e escolha o recorte do quadro.</Typography></Box><SectionInfo title="Use a pesquisa para localizar sintomas, soluções, tickets ou tarefas. Os seletores abaixo alteram apenas a visualização do quadro e podem ser combinados."/></Stack><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,minmax(0,1fr))",xl:"minmax(320px,1.35fr) repeat(3,minmax(150px,.7fr)) auto"},gap:1,alignItems:"center"}}><TextField fullWidth size="small" value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar erro, sintoma, rotina, ticket, APOIO ou solução..." slotProps={{input:{startAdornment:<SearchRounded sx={{mr:1,color:"text.secondary"}}/>}}}/><TextField select size="small" label="Visão" value={view} onChange={e=>setView(e.target.value as typeof view)}><MenuItem value="all">Todos os registros</MenuItem><MenuItem value="active">Somente ativos</MenuItem><MenuItem value="critical">Críticos ativos</MenuItem><MenuItem value="pinned">Fixados</MenuItem></TextField><TextField select size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="">Todos</MenuItem>{Object.entries(statusLabel).map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField select size="small" label="Criticidade" value={severity} onChange={e=>setSeverity(e.target.value)}><MenuItem value="">Todas</MenuItem>{["BAIXA","MEDIA","ALTA","CRITICA"].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><Button variant="contained" startIcon={<SearchRounded/>} onClick={()=>navigate(`/investigacao?q=${encodeURIComponent(q)}`)} disabled={q.trim().length<2} sx={{whiteSpace:"nowrap",minWidth:118,height:40}}>Investigar</Button></Box></CardContent></Card>
  <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"repeat(2,minmax(0,1fr))"},gap:1.25}}>
   {visibleItems.map(item=><Card id={`known-problem-${item.id}`} key={item.id} variant="outlined" sx={{position:"relative",overflow:"hidden",transition:"transform .18s ease,border-color .18s ease,box-shadow .18s ease",borderColor:focusedProblem===item.id?"primary.main":undefined,boxShadow:focusedProblem===item.id?(theme.palette.mode==="dark"?"0 0 0 2px rgba(24,199,122,.16), 0 18px 42px rgba(0,0,0,.24)":"0 0 0 2px rgba(24,199,122,.12), 0 16px 34px rgba(15,23,42,.09)"):undefined,"&:hover":{transform:"translateY(-2px)",borderColor:"rgba(24,199,122,.35)",boxShadow:theme.palette.mode==="dark"?"0 16px 38px rgba(0,0,0,.24)":"0 14px 32px rgba(15,23,42,.09)"}}}><CardContent>
    <Stack direction="row" spacing={1} sx={{alignItems:"flex-start"}}><Box sx={{width:42,height:42,borderRadius:2,display:"grid",placeItems:"center",background:"rgba(24,199,122,.10)",color:aliareColors.green,flexShrink:0}}><CampaignOutlined/></Box><Box sx={{flex:1,minWidth:0}}><Stack direction="row" spacing={.7} sx={{flexWrap:"wrap",alignItems:"center"}}>{item.pinned&&<PushPinOutlined sx={{fontSize:16,color:aliareColors.warning}}/>}<Typography sx={{fontWeight:900,fontSize:"1.02rem"}}>{item.title}</Typography></Stack><Stack direction="row" spacing={.6} sx={{mt:.6,flexWrap:"wrap"}}><Chip size="small" label={statusLabel[item.status]??item.status} color={item.status==="RESOLVIDO"?"success":"default"}/><Chip size="small" label={item.severity} color={severityColor[item.severity]}/>{item.service&&<Chip size="small" variant="outlined" label={item.service}/>}</Stack></Box><IconButton size="small" aria-label={`Editar problema conhecido ${item.title}`} onClick={()=>edit(item)}><EditOutlined fontSize="small"/></IconButton></Stack>
    <Box sx={{mt:1.5,p:1.3,borderRadius:1.5,bgcolor:"action.hover"}}><Typography variant="caption" color="text.secondary" sx={{fontWeight:800}}>COMO IDENTIFICAR</Typography><Typography variant="body2" sx={{whiteSpace:"pre-wrap",mt:.3}}>{item.symptom}</Typography></Box>
    {item.cause&&<Box sx={{mt:1.1,p:1.3,borderRadius:1.5,bgcolor:"action.hover"}}><Typography variant="caption" color="text.secondary" sx={{fontWeight:850}}>CAUSA</Typography><Typography variant="body2" sx={{whiteSpace:"pre-wrap",mt:.3}}>{item.cause}</Typography></Box>}<Box sx={{mt:1.1,p:1.3,borderRadius:1.5,border:"1px solid rgba(24,199,122,.18)",background:"rgba(24,199,122,.045)"}}><Typography variant="caption" sx={{fontWeight:850,color:aliareColors.green}}>SOLUÇÃO</Typography><Typography variant="body2" sx={{whiteSpace:"pre-wrap",mt:.3}}>{item.technicalSolution||item.solution}</Typography></Box>{item.workaround&&<Box sx={{mt:1.1,p:1.3,borderRadius:1.5,border:"1px solid",borderColor:"warning.main"}}><Typography variant="caption" color="warning.main" sx={{fontWeight:850}}>PALIATIVO</Typography><Typography variant="body2" sx={{whiteSpace:"pre-wrap",mt:.3}}>{item.workaround}</Typography></Box>}{item.comment&&<Box sx={{mt:1.1,p:1.2,borderRadius:1.5,bgcolor:"action.hover"}}><Typography variant="caption" color="text.secondary" sx={{fontWeight:850}}>COMENTÁRIO INTERNO</Typography><Typography variant="body2" sx={{whiteSpace:"pre-wrap",mt:.3}}>{item.comment}</Typography></Box>}
    <Stack direction="row" spacing={.7} sx={{mt:1.2,flexWrap:"wrap"}}>{item.movideskTicket&&<Chip clickable size="small" variant="outlined" label={`Ticket #${item.movideskTicket}`} onClick={()=>navigate(`/tickets?movidesk=${item.movideskTicket}`)}/>} {item.azureWorkItem&&<Chip clickable size="small" variant="outlined" label={`${item.azureWorkItemType||"Azure"} #${item.azureWorkItem}`} onClick={()=>openAzure(item)}/>} {item.version&&<Chip size="small" variant="outlined" label={`Versão ${item.version}`}/>} {item.client&&<Chip size="small" variant="outlined" label={item.client}/>}</Stack>
    <Stack direction="row" sx={{mt:1.4,alignItems:"center",justifyContent:"space-between",gap:1}}><Typography variant="caption" color="text.secondary">Atualizado por {item.updatedByName??"time"} · {new Date(item.updatedAt).toLocaleString("pt-BR")} · {item.readCount} leitura(s)</Typography><Button size="small" startIcon={<VisibilityOutlined/>} onClick={()=>void read(item.id)}>Marcar como lido</Button></Stack>
   </CardContent></Card>)}
  </Box>
  {!visibleItems.length&&<Card variant="outlined" sx={{mt:2,borderStyle:"dashed"}}><CardContent sx={{py:4,textAlign:"center"}}><SearchRounded sx={{fontSize:34,color:"text.disabled"}}/><Typography sx={{fontWeight:850,mt:1}}>Nenhum problema conhecido neste recorte</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>Ajuste a pesquisa, a visão, o status ou a criticidade para ampliar o radar operacional.</Typography><Button sx={{mt:1.5}} onClick={()=>{setQ("");setView("all");setStatus("");setSeverity("");}}>Limpar filtros</Button></CardContent></Card>}
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>{editing?"Editar problema conhecido":"Nova publicação operacional"}</DialogTitle><DialogContent><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)"},gap:1.5,pt:1}}>
   <Autocomplete options={sources} loading={sourceLoading} filterOptions={x=>x} getOptionLabel={x=>x.label} onInputChange={(_,v)=>setSourceQuery(v)} onChange={(_,v)=>applySource(v)} sx={{gridColumn:{md:"1 / -1"}}} renderInput={params=><TextField {...params} label="Buscar atendimento, Correção, Evolução ou APOIO" placeholder="Ex.: COAP fixação saldo, receituário AgriQ ou 810063..." helperText="Busca contextual: combine palavras de título, cliente, serviço, módulo, processo, descrição ou número. Não precisa digitar o texto exato."/>}/>
   <TextField label="Título do problema" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} sx={{gridColumn:{md:"1 / -1"}}}/>
   <TextField label="Serviço / rotina" value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/><TextField label="Cliente (opcional)" value={form.client} onChange={e=>setForm({...form,client:e.target.value})}/>
   <TextField multiline minRows={3} label="Sintoma / como identificar" value={form.symptom} onChange={e=>setForm({...form,symptom:e.target.value})} sx={{gridColumn:{md:"1 / -1"}}}/>
   <TextField multiline minRows={4} label="Solução / paliativo / passo a passo" value={form.solution} onChange={e=>setForm({...form,solution:e.target.value})} sx={{gridColumn:{md:"1 / -1"}}}/>
   <TextField label="Ticket Movidesk" value={form.movideskTicket} onChange={e=>setForm({...form,movideskTicket:e.target.value})} onBlur={()=>void syncReference("ticket",form.movideskTicket)} helperText="Ao informar o número, os dados sincronizados são carregados."/><TextField label="Correção / Evolução / APOIO" value={form.azureWorkItem} onChange={e=>setForm({...form,azureWorkItem:e.target.value})} onBlur={()=>void syncReference("workItem",form.azureWorkItem)} helperText="Ao informar a tarefa, o título, Considerações de Desenvolvimento e Descrição Solução Paliativa são sincronizados quando preenchidos."/>
   <TextField label="Versão" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/><TextField label="Tags" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/>
   <TextField select label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statusLabel).map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField>
   <TextField select label="Criticidade" value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{["BAIXA","MEDIA","ALTA","CRITICA"].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField>
   <FormControlLabel control={<Switch checked={form.pinned} onChange={e=>setForm({...form,pinned:e.target.checked})}/>} label="Fixar no topo do quadro"/>
  </Box></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={saving||!form.title||!form.symptom||!form.solution} onClick={()=>void save()}>{saving?"Salvando...":"Publicar atualização"}</Button></DialogActions></Dialog>
 </Box>
}