import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, InputAdornment, LinearProgress, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { AccountTreeOutlined, SearchOutlined, UploadFileOutlined, HubOutlined, PsychologyOutlined, FolderOpenOutlined, RuleOutlined, AltRouteOutlined, AssessmentOutlined } from "@mui/icons-material";
import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { SimerMapTree, type SimerTreeNode } from "../components/SimerMapTree";
import { SystemRulePanel } from "../components/SystemRulePanel";
import { SystemExplorer } from "../components/SystemExplorer";
import { api } from "../services/api";
import { aliareColors } from "../theme/theme";

type Summary={total:number;maps:number;links:number;importedAt:string|null;builderApiUrl:string;items:Array<{mapName:string;total:number}>;kinds:Array<{kind:string;total:number}>};
type Result={id:number;sourceFile:string;mapName:string;nodeId:string|null;nodeText:string;path:string;depth:number;parentPath:string|null;icon:string|null;link:string|null;nodeKind:string|null;score?:number;matchedTerms?:string[];correlationScore?:number;correlationTerms?:string[];reasons?:string[]};
type Investigation={mapItems:Result[];ruleItems:Array<{id:number;processId:number;name:string;processName:string}>;correlations:Result[]};
const folderProps={webkitdirectory:"",directory:""} as Record<string,string>;

export function SimerMap(){
 const [searchParams]=useSearchParams(); const autoContextDone=useRef(false);
 const[tree,setTree]=useState<SimerTreeNode[]>([]),[treeMap,setTreeMap]=useState(""),[treeLoading,setTreeLoading]=useState(false),[treeFocusId,setTreeFocusId]=useState<number|null>(null);
 const[mode,setMode]=useState<"tree"|"investigate"|"bases">("tree"),[summary,setSummary]=useState<Summary|null>(null),[query,setQuery]=useState(""),[context,setContext]=useState(""),[items,setItems]=useState<Result[]>([]),[correlations,setCorrelations]=useState<Result[]>([]),[ruleMatches,setRuleMatches]=useState(0),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[progress,setProgress]=useState<number|null>(null);
 const loadSummary=useCallback(async()=>{const r=await api.get<Summary>("/simer-map/summary");setSummary(r.data);},[]);
 useEffect(()=>{void loadSummary();},[loadSummary]);
 useEffect(()=>{const incoming=searchParams.get("context");if(!incoming||autoContextDone.current)return;autoContextDone.current=true;setMode("investigate");setContext(incoming);setLoading(true);void api.post<{items:Result[]}>("/simer-map/context",{text:incoming,limit:30}).then(r=>{setItems(r.data.items);setMessage(`Investigação sugerida para o atendimento #${searchParams.get("ticket")??""}.`);}).catch(()=>setMessage("Não foi possível analisar o contexto do atendimento.")).finally(()=>setLoading(false));},[searchParams]);

 async function search(){if(!query.trim()){setItems([]);return;}setLoading(true);setMessage("");try{const r=await api.get<{items:Result[]}>("/simer-map/search",{params:{q:query.trim()}});setItems(r.data.items);}catch{setMessage("Não foi possível consultar o Mapa SIMER.");}finally{setLoading(false);}}
 async function analyze(){if(!context.trim())return;setLoading(true);try{const r=await api.post<Investigation>("/simer-map/investigate",{text:context});setItems(r.data.mapItems);setCorrelations(r.data.correlations);setRuleMatches(r.data.ruleItems.length);setMessage(r.data.correlations.length?`Investigação cruzada: ${r.data.ruleItems.length} regra(s) e ${r.data.correlations.length} ponto(s) técnico(s) correlacionados.`:"Não foi possível formar uma correlação forte; os resultados individuais continuam disponíveis.");}finally{setLoading(false);}}
 async function openTree(item:Result){setTreeMap(item.mapName);setTreeFocusId(item.id);setTree([]);setTreeLoading(true);setMessage("");try{const r=await api.get<{items:SimerTreeNode[]}>("/simer-map/tree",{params:{sourceFile:item.sourceFile,focusId:item.id}});setTree(r.data.items);if(!r.data.items.length)setMessage(`Nenhum nó encontrado para o mapa ${item.mapName}.`);}catch{setMessage(`Não foi possível abrir a árvore de ${item.mapName}.`);}finally{setTreeLoading(false);}}
 async function openContainer(node:SimerTreeNode){setTreeLoading(true);setMessage("");try{const resolved=await api.get<{item:Result|null}>(`/simer-map/nodes/${node.id}/container`);const target=resolved.data.item;if(!target){setMessage(`O container referenciado em ${node.nodeText} não foi encontrado nos mapas importados.`);return;}const r=await api.get<{items:SimerTreeNode[]}>("/simer-map/tree",{params:{sourceFile:target.sourceFile,focusId:target.id}});setTreeMap(target.mapName);setTreeFocusId(target.id);setTree(r.data.items);}catch{setMessage("Não foi possível abrir a definição do container.");}finally{setTreeLoading(false);}}
 async function followMapLink(node:SimerTreeNode){if(!node.link)return;setTreeLoading(true);setMessage("");try{const resolved=await api.get<{item:Result|null}>(`/simer-map/nodes/${node.id}/follow`);const target=resolved.data.item;if(!target){setMessage(`O mapa vinculado a ${node.nodeText} não foi encontrado na base SIMER.`);return;}const r=await api.get<{items:SimerTreeNode[]}>("/simer-map/tree",{params:{sourceFile:target.sourceFile,focusId:target.id}});setTreeMap(target.mapName);setTreeFocusId(target.id);setTree(r.data.items);}catch{setMessage("Não foi possível navegar para o mapa vinculado.");}finally{setTreeLoading(false);}}
 async function importFiles(list:FileList|null){if(!list?.length)return;const files=Array.from(list).filter(f=>f.name.toLowerCase().endsWith(".mm"));if(!files.length){setMessage("Nenhum arquivo .mm encontrado.");return;}setLoading(true);setProgress(0);setMessage("");try{let nodes=0;for(let i=0;i<files.length;i+=8){const chunk=files.slice(i,i+8);const payload=await Promise.all(chunk.map(async file=>({sourceFile:(file as File&{webkitRelativePath?:string}).webkitRelativePath||file.name,content:await file.text()})));const r=await api.post<{nodes:number}>("/simer-map/import/batch",{files:payload});nodes+=r.data.nodes;setProgress(Math.round(Math.min(i+chunk.length,files.length)/files.length*100));}setMessage(`Base atualizada: ${files.length} mapa(s) e ${nodes.toLocaleString("pt-BR")} nó(s) processados.`);await loadSummary();}catch(e:unknown){setMessage((e as {response?:{data?:{message?:string}}}).response?.data?.message??"Falha ao importar os mapas.");}finally{setLoading(false);setProgress(null);}}
 return <Box sx={{pb:4}}>
  <Card variant="outlined" sx={{borderRadius:3,overflow:"hidden",bgcolor:"background.paper"}}><Box sx={{px:{xs:1.5,md:2},py:1.25,display:"grid",gridTemplateColumns:{xs:"1fr",lg:"320px minmax(360px,650px) 1fr"},gap:2,alignItems:"center"}}><Stack direction="row" spacing={1.2} sx={{alignItems:"center"}}><Box sx={{width:42,height:42,borderRadius:2.2,display:"grid",placeItems:"center",bgcolor:"#0b2230",color:"#22d39a"}}><HubOutlined/></Box><Box><Typography variant="h6" sx={{fontWeight:950,lineHeight:1.1}}>Mapa e Fluxo SIMER</Typography><Typography variant="caption" color="text.secondary">Estrutura, regras e mapas técnicos integrados.</Typography></Box></Stack><TextField size="small" value={context} onChange={e=>setContext(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setMode("investigate");void analyze();}}} placeholder="Buscar no sistema: rotina, regra, campo, serviço..." slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchOutlined fontSize="small"/></InputAdornment>,endAdornment:<InputAdornment position="end"><Chip size="small" label="Ctrl + K"/></InputAdornment>}}}/><Typography variant="caption" color="text.secondary" sx={{textAlign:{lg:"right"}}}>{summary?`${summary.maps.toLocaleString("pt-BR")} mapas · ${summary.total.toLocaleString("pt-BR")} nós técnicos`:"Base aguardando importação"}</Typography></Box><Divider/><Tabs value={mode} onChange={(_,v)=>setMode(v)} variant="scrollable" scrollButtons="auto" sx={{px:1,minHeight:44,"& .MuiTab-root":{minHeight:44,fontWeight:750,textTransform:"none"}}}><Tab value="tree" icon={<AccountTreeOutlined/>} iconPosition="start" label="Árvore do Sistema"/><Tab value="investigate" icon={<SearchOutlined/>} iconPosition="start" label="Busca Contextual"/><Tab value="bases" icon={<RuleOutlined/>} iconPosition="start" label="Regras e Mapas"/><Tab value="tree" icon={<AltRouteOutlined/>} iconPosition="start" label="Cadeia de Processos"/><Tab value="tree" icon={<AssessmentOutlined/>} iconPosition="start" label="Visão Integrada"/></Tabs></Card>
  {mode==="tree"&&<SystemExplorer onOpenMap={item=>void openTree(item as Result)}/>}
  {mode==="investigate"&&<><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"1fr 1fr"},gap:2,mt:2}}>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><PsychologyOutlined sx={{color:aliareColors.green}}/><Box><Typography sx={{fontWeight:900}}>Buscar por contexto funcional</Typography><Typography variant="caption" color="text.secondary">Descreva a sequência funcional para localizar o ponto mais provável no mapa.</Typography></Box></Stack><Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField fullWidth value={context} onChange={e=>setContext(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void analyze()} placeholder="Ex.: pedido de venda item lote" helperText="Use termos do processo em sequência: rotina → seção → campo. Ex.: pedido de venda → item → lote."/><Button variant="contained" onClick={()=>void analyze()} disabled={loading} sx={{alignSelf:{md:"flex-start"}}}>Localizar</Button></Stack></CardContent></Card>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><SearchOutlined sx={{color:aliareColors.green}}/><Box><Typography sx={{fontWeight:900}}>Consulta técnica</Typography><Typography variant="caption" color="text.secondary">Busca direta por mapa, container, classe, serviço ou nome técnico.</Typography></Box></Stack><Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField fullWidth value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void search()} placeholder="PedidoCompra, ContainerRateio, saldo..." slotProps={{input:{startAdornment:<InputAdornment position="start"><AccountTreeOutlined/></InputAdornment>}}}/><Button variant="outlined" onClick={()=>void search()} disabled={loading}>Consultar</Button></Stack></CardContent></Card>
  </Box>
  {correlations.length>0&&<Card variant="outlined" sx={{mt:2,borderRadius:3,borderColor:"primary.main"}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1.5}}><HubOutlined color="primary"/><Box><Typography sx={{fontWeight:950}}>Cadeia inteligente da investigação</Typography><Typography variant="body2" color="text.secondary">Cruzamento automático entre {ruleMatches} regra(s) funcional(is) e o mapa técnico. Os pontos abaixo são os candidatos com maior associação semântica.</Typography></Box></Stack><Stack spacing={1}>{correlations.slice(0,8).map(item=><Box key={item.id} sx={{p:1.3,border:"1px solid",borderColor:"divider",borderRadius:2.5,bgcolor:"background.paper"}}><Stack direction="row" spacing={.7} useFlexGap sx={{flexWrap:"wrap",alignItems:"center"}}><Chip size="small" color="success" label={`correlação ${item.correlationScore??0}`}/><Chip size="small" variant="outlined" label={item.mapName}/><Chip size="small" label={item.nodeKind||"nó"}/><Typography sx={{fontWeight:850}}>{item.nodeText}</Typography></Stack><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>{item.path}</Typography>{item.reasons?.map(x=><Chip key={x} size="small" variant="outlined" sx={{mt:.7,mr:.5}} label={x}/>)}<Button size="small" sx={{mt:.5}} onClick={()=>void openTree(item)}>Abrir ponto técnico</Button></Box>)}</Stack></CardContent></Card>}
  <Box sx={{mt:2}}><SystemRulePanel initialQuery={context||query}/></Box></>}
  {mode==="bases"&&<><SystemRulePanel initialQuery={context||query}/><Card variant="outlined" sx={{mt:2,borderRadius:3}}><CardContent sx={{p:{xs:2,md:2.5},"&:last-child":{pb:{xs:2,md:2.5}}}}><Stack direction={{xs:"column",lg:"row"}} spacing={1.5} sx={{justifyContent:"space-between",alignItems:{lg:"center"}}}><Box sx={{display:"flex",alignItems:"center",gap:1.2}}><Box sx={{width:40,height:40,borderRadius:2,display:"grid",placeItems:"center",bgcolor:"action.hover"}}><AccountTreeOutlined sx={{color:aliareColors.green}}/></Box><Box><Typography sx={{fontWeight:900}}>Base técnica dos mapas</Typography><Typography variant="body2" color="text.secondary">Gerencie os arquivos .mm usados na investigação técnica. Arquivos existentes são atualizados automaticamente.</Typography></Box></Box><Stack direction="row" spacing={1} useFlexGap sx={{flexWrap:"wrap"}}><Button component="label" variant="outlined" size="small" startIcon={<UploadFileOutlined/>}>Arquivos .mm<input hidden type="file" multiple accept=".mm" onChange={e=>void importFiles(e.target.files)}/></Button><Button component="label" variant="contained" size="small" startIcon={<FolderOpenOutlined/>}>Importar pasta<input hidden type="file" multiple {...folderProps} onChange={e=>void importFiles(e.target.files)}/></Button></Stack></Stack>{progress!==null&&<Box sx={{mt:1.5}}><LinearProgress variant="determinate" value={progress}/><Typography variant="caption">{progress}% processado</Typography></Box>}{summary&&<Stack direction="row" spacing={.7} useFlexGap sx={{flexWrap:"wrap",mt:1.5}}><Chip size="small" variant="outlined" label={`${summary.maps.toLocaleString("pt-BR")} mapas`}/><Chip size="small" variant="outlined" label={`${summary.total.toLocaleString("pt-BR")} nós técnicos`}/><Chip size="small" variant="outlined" label={`${summary.links.toLocaleString("pt-BR")} relacionamentos`}/>{summary.kinds?.map(x=><Chip size="small" key={x.kind} label={`${x.kind} · ${x.total.toLocaleString("pt-BR")}`}/>)}</Stack>}{message&&<Alert severity={message.includes("Falha")||message.includes("Nenhum")?"warning":"success"} sx={{mt:1.5}}>{message}</Alert>}</CardContent></Card>
  </>}
  {mode==="investigate"&&<Box sx={{mt:2}}>{loading&&progress===null?<Box sx={{py:5,textAlign:"center"}}><CircularProgress/></Box>:items.length?<Stack spacing={1}>{items.map(item=><Box key={item.id}><Card variant="outlined" sx={{borderRadius:2.5,cursor:"pointer",borderColor:treeFocusId===item.id?"primary.main":undefined,"&:hover":{borderColor:aliareColors.green,transform:"translateY(-1px)",boxShadow:"0 10px 28px rgba(16,24,40,.07)"}}}><CardContent sx={{py:1.3,"&:last-child":{pb:1.3}}}><Stack direction="row" spacing={.8} useFlexGap sx={{flexWrap:"wrap",alignItems:"center"}}><Chip size="small" icon={<HubOutlined/>} label={item.nodeKind||"nó"}/><Chip size="small" variant="outlined" label={item.mapName}/>{item.score&&<Chip size="small" color="success" label={`relevância ${item.score}`}/>}<Typography sx={{fontWeight:850}}>{item.nodeText}</Typography></Stack><Typography variant="body2" color="text.secondary" sx={{mt:.6}}>{item.path}</Typography><Stack direction="row" spacing={1} sx={{alignItems:"center",mt:.5}}>{item.link&&<Typography variant="caption" color="primary.main">↗ {item.link}</Typography>}<Button size="small" onClick={e=>{e.stopPropagation();void openTree(item);}}>{treeFocusId===item.id&&tree.length?"Mapa aberto":"Abrir no mapa"}</Button></Stack></CardContent></Card>{treeFocusId===item.id&&(treeLoading||tree.length>0)&&<Card variant="outlined" sx={{mt:1,borderRadius:3,borderColor:"primary.main"}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><Typography sx={{fontWeight:900,fontSize:"1.05rem"}}>{treeMap}</Typography><Chip size="small" label="Recorte do mapa"/><Button size="small" onClick={()=>{setTree([]);setTreeMap("");setTreeFocusId(null);}}>Fechar mapa</Button></Stack>{treeLoading?<Box sx={{py:4,textAlign:"center"}}><CircularProgress size={28}/><Typography variant="body2" color="text.secondary" sx={{mt:1}}>Carregando ponto do mapa...</Typography></Box>:<SimerMapTree items={tree} focusId={treeFocusId} onSelect={node=>setTreeFocusId(node.id)} onFollowLink={node=>void followMapLink(node)} onOpenContainer={node=>void openContainer(node)}/>}</CardContent></Card>}</Box>)}</Stack>:null}</Box>}


 </Box>;
}