import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, InputAdornment, LinearProgress, Stack, TextField, Typography } from "@mui/material";
import { AccountTreeOutlined, SearchOutlined, UploadFileOutlined, OpenInNewOutlined, HubOutlined, PsychologyOutlined, FolderOpenOutlined } from "@mui/icons-material";
import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { SimerMapTree, type SimerTreeNode } from "../components/SimerMapTree";
import { api } from "../services/api";
import { aliareColors } from "../theme/theme";

type Summary={total:number;maps:number;links:number;importedAt:string|null;builderApiUrl:string;items:Array<{mapName:string;total:number}>;kinds:Array<{kind:string;total:number}>};
type Result={id:number;sourceFile:string;mapName:string;nodeId:string|null;nodeText:string;path:string;depth:number;parentPath:string|null;icon:string|null;link:string|null;nodeKind:string|null;score?:number;matchedTerms?:string[]};
type Builder={reachable:boolean;status:number|null;latencyMs:number};
const folderProps={webkitdirectory:"",directory:""} as Record<string,string>;

export function SimerMap(){
 const [searchParams]=useSearchParams(); const autoContextDone=useRef(false); const treeRef=useRef<HTMLDivElement|null>(null);
 const[tree,setTree]=useState<SimerTreeNode[]>([]),[treeMap,setTreeMap]=useState(""),[treeLoading,setTreeLoading]=useState(false),[treeFocusId,setTreeFocusId]=useState<number|null>(null);
 const[summary,setSummary]=useState<Summary|null>(null),[query,setQuery]=useState(""),[context,setContext]=useState(""),[items,setItems]=useState<Result[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[progress,setProgress]=useState<number|null>(null),[builder,setBuilder]=useState<Builder|null>(null);
 const loadSummary=useCallback(async()=>{const r=await api.get<Summary>("/simer-map/summary");setSummary(r.data);},[]);
 useEffect(()=>{void loadSummary();void api.get<Builder>("/simer-map/builder/status").then(r=>setBuilder(r.data)).catch(()=>setBuilder({reachable:false,status:null,latencyMs:0}));},[loadSummary]);
 useEffect(()=>{const incoming=searchParams.get("context");if(!incoming||autoContextDone.current)return;autoContextDone.current=true;setContext(incoming);setLoading(true);void api.post<{items:Result[]}>("/simer-map/context",{text:incoming,limit:30}).then(r=>{setItems(r.data.items);setMessage(`Investigação sugerida para o atendimento #${searchParams.get("ticket")??""}.`);}).catch(()=>setMessage("Não foi possível analisar o contexto do atendimento.")).finally(()=>setLoading(false));},[searchParams]);

 async function search(){if(!query.trim()){setItems([]);return;}setLoading(true);setMessage("");try{const r=await api.get<{items:Result[]}>("/simer-map/search",{params:{q:query.trim()}});setItems(r.data.items);}catch{setMessage("Não foi possível consultar o Mapa SIMER.");}finally{setLoading(false);}}
 async function analyze(){if(!context.trim())return;setLoading(true);try{const r=await api.post<{items:Result[]}>("/simer-map/context",{text:context,limit:30});setItems(r.data.items);setMessage(r.data.items.length?"Pontos técnicos sugeridos a partir do contexto informado.":"Nenhuma correspondência relevante encontrada.");}finally{setLoading(false);}}
 async function openTree(item:Result){setTreeMap(item.mapName);setTreeFocusId(item.id);setTree([]);setTreeLoading(true);setMessage("");requestAnimationFrame(()=>treeRef.current?.scrollIntoView({behavior:"smooth",block:"start"}));try{const r=await api.get<{items:SimerTreeNode[]}>("/simer-map/tree",{params:{sourceFile:item.sourceFile}});setTree(r.data.items);if(!r.data.items.length)setMessage(`Nenhum nó encontrado para o mapa ${item.mapName}.`);}catch{setMessage(`Não foi possível abrir a árvore de ${item.mapName}.`);}finally{setTreeLoading(false);}}
 async function importFiles(list:FileList|null){if(!list?.length)return;const files=Array.from(list).filter(f=>f.name.toLowerCase().endsWith(".mm"));if(!files.length){setMessage("Nenhum arquivo .mm encontrado.");return;}setLoading(true);setProgress(0);setMessage("");try{let nodes=0;for(let i=0;i<files.length;i+=8){const chunk=files.slice(i,i+8);const payload=await Promise.all(chunk.map(async file=>({sourceFile:(file as File&{webkitRelativePath?:string}).webkitRelativePath||file.name,content:await file.text()})));const r=await api.post<{nodes:number}>("/simer-map/import/batch",{files:payload});nodes+=r.data.nodes;setProgress(Math.round(Math.min(i+chunk.length,files.length)/files.length*100));}setMessage(`Base atualizada: ${files.length} mapa(s) e ${nodes.toLocaleString("pt-BR")} nó(s) processados.`);await loadSummary();}catch(e:unknown){setMessage((e as {response?:{data?:{message?:string}}}).response?.data?.message??"Falha ao importar os mapas.");}finally{setLoading(false);setProgress(null);}}
 const cards=[["Mapas",summary?.maps??0],["Nós técnicos",summary?.total??0],["Relacionamentos",summary?.links??0],["Builder API",builder?.reachable?"Online":"Indisponível"]];
 return <Box sx={{pb:4}}>
  <PageHeader eyebrow="Liderança técnica" title="Mapa SIMER" description="Mapa técnico navegável para apoiar diagnóstico, investigação de atendimentos e abertura de Correções/Apoios." meta={summary?.importedAt?`Atualizado em ${new Date(summary.importedAt).toLocaleString("pt-BR")}`:"Base aguardando importação"}/>
  <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr 1fr",lg:"repeat(4,1fr)"},gap:1.5,mt:2}}>{cards.map(([label,value])=><Card key={String(label)} variant="outlined" sx={{borderRadius:3,borderTop:"3px solid",borderTopColor:label==="Builder API"?(builder?.reachable?"success.main":"warning.main"):aliareColors.green}}><CardContent><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" sx={{fontWeight:900,mt:.3}}>{typeof value==="number"?value.toLocaleString("pt-BR"):value}</Typography></CardContent></Card>)}</Box>
  <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",xl:"1.35fr 1fr"},gap:2,mt:2}}>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{ alignItems: "center", mb: 1 }}><SearchOutlined sx={{color:aliareColors.green}}/><Typography sx={{fontWeight:900}}>Consulta técnica</Typography></Stack><Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField fullWidth value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void search()} placeholder="PedidoCompra, ContainerRateio, saldo, programação..." slotProps={{input:{startAdornment:<InputAdornment position="start"><AccountTreeOutlined/></InputAdornment>}}}/><Button variant="contained" onClick={()=>void search()} disabled={loading}>Consultar</Button></Stack></CardContent></Card>
   <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{ alignItems: "center", mb: 1 }}><PsychologyOutlined sx={{color:aliareColors.green}}/><Typography sx={{fontWeight:900}}>Analisar contexto do atendimento</Typography></Stack><Stack direction="row" spacing={1}><TextField fullWidth size="small" value={context} onChange={e=>setContext(e.target.value)} placeholder="Cole assunto, erro ou descrição do atendimento..."/><Button variant="outlined" onClick={()=>void analyze()} disabled={loading}>Sugerir</Button></Stack></CardContent></Card>
  </Box>
  <Card variant="outlined" sx={{mt:2,borderRadius:3}}><CardContent><Stack direction={{xs:"column",lg:"row"}} spacing={1.5} sx={{ justifyContent: "space-between", alignItems: { lg: "center" } }}><Box><Typography sx={{fontWeight:900}}>Base técnica dos mapas</Typography><Typography variant="body2" color="text.secondary">Importe a pasta extraída de Mapas.zip. A estrutura relativa é preservada e arquivos existentes são atualizados.</Typography></Box><Stack direction="row" spacing={1}><Button component="label" variant="outlined" startIcon={<UploadFileOutlined/>}>Arquivos .mm<input hidden type="file" multiple accept=".mm" onChange={e=>void importFiles(e.target.files)}/></Button><Button component="label" variant="contained" startIcon={<FolderOpenOutlined/>}>Importar pasta<input hidden type="file" multiple {...folderProps} onChange={e=>void importFiles(e.target.files)}/></Button></Stack></Stack>{progress!==null&&<Box sx={{mt:1.5}}><LinearProgress variant="determinate" value={progress}/><Typography variant="caption">{progress}% processado</Typography></Box>}{summary?.kinds?.length?<Stack direction="row" spacing={.7} useFlexGap sx={{ flexWrap: "wrap", mt: 1.5 }}>{summary.kinds.map(x=><Chip size="small" key={x.kind} label={`${x.kind} · ${x.total.toLocaleString("pt-BR")}`}/>)}</Stack>:null}{message&&<Alert severity={message.includes("Falha")||message.includes("Nenhum")?"warning":"success"} sx={{mt:1.5}}>{message}</Alert>}</CardContent></Card>
  <Card variant="outlined" sx={{mt:2,borderRadius:3}}><CardContent><Stack direction="row" sx={{ justifyContent: "space-between", alignItems: "center" }}><Box><Typography sx={{fontWeight:900}}>Builder API</Typography><Typography variant="caption" color="text.secondary">{summary?.builderApiUrl} {builder&&`· ${builder.reachable?"conectado":"sem resposta"} · ${builder.latencyMs} ms`}</Typography></Box><Button component="a" href={summary?.builderApiUrl} target="_blank" rel="noreferrer" size="small" endIcon={<OpenInNewOutlined/>}>Abrir</Button></Stack></CardContent></Card>
  <Box sx={{mt:2}}>{loading&&progress===null?<Box sx={{py:5,textAlign:"center"}}><CircularProgress/></Box>:items.length?<Stack spacing={1}>{items.map(item=><Card key={item.id} variant="outlined" onClick={()=>void inspect(item)} sx={{borderRadius:2.5,cursor:"pointer","&:hover":{borderColor:aliareColors.green,transform:"translateY(-1px)",boxShadow:"0 10px 28px rgba(16,24,40,.07)"}}}><CardContent sx={{py:1.3,"&:last-child":{pb:1.3}}}><Stack direction="row" spacing={.8} useFlexGap sx={{ flexWrap: "wrap", alignItems: "center" }}><Chip size="small" icon={<HubOutlined/>} label={item.nodeKind||"nó"}/><Chip size="small" variant="outlined" label={item.mapName}/>{item.score&&<Chip size="small" color="success" label={`relevância ${item.score}`}/>}<Typography sx={{fontWeight:850}}>{item.nodeText}</Typography></Stack><Typography variant="body2" color="text.secondary" sx={{ mt: .6 }}>{item.path}</Typography><Stack direction="row" spacing={1} sx={{alignItems:"center",mt:.5}}>{item.link&&<Typography variant="caption" color="primary.main">↗ {item.link}</Typography>}<Button size="small" onClick={e=>{e.stopPropagation();void openTree(item);}}>Abrir no mapa</Button></Stack></CardContent></Card>)}</Stack>:null}</Box>
  {(treeLoading||tree.length>0)&&<Box ref={treeRef} sx={{scrollMarginTop:16}}><Card variant="outlined" sx={{mt:2,borderRadius:3}}><CardContent><Stack direction="row" spacing={1} sx={{alignItems:"center",mb:1}}><Typography sx={{fontWeight:900,fontSize:"1.05rem"}}>{treeMap}</Typography><Chip size="small" label="Visualização hierárquica"/><Button size="small" onClick={()=>{setTree([]);setTreeMap("");setTreeFocusId(null);}}>Fechar mapa</Button></Stack>{treeLoading?<Box sx={{py:5,textAlign:"center"}}><CircularProgress size={28}/><Typography variant="body2" color="text.secondary" sx={{mt:1}}>Carregando estrutura completa...</Typography></Box>:<SimerMapTree items={tree} focusId={treeFocusId} onSelect={node=>{setTreeFocusId(node.id);}}/>}</CardContent></Card></Box>}

 </Box>;
}